namespace Konserva.Localization;

public static class EnglishStrings
{
    public static readonly Dictionary<string, string> Translations = new Dictionary<string, string>
    {
        { "MainWindow_Settings", "Settings" },
        { "MainWindow_Header", "Konserva Manager" },
        { "StatusBar_TotalServers", "Total Servers" },
        { "StatusBar_Running", "Running" },
        { "StatusBar_Memory", "Memory" },
        { "Update_Button", "Update" },
        { "Update_Downloading", "Downloading..." },
        { "Update_Installing", "Installing..." },
        { "Update_Success", "Restarting..." },
        { "Update_Retry", "Retry" },
        { "Update_Available_Tooltip", "Click to update" },
        { "Update_Failed_Tooltip", "Update failed. Click to retry." },
        { "Settings_CheckForUpdates", "Check for Updates" },
        { "Settings_UpToDate_Button", "Up to Date" },
        { "Settings_UpdateAvailable_Button", "Update Available {0}" },
        { "Settings_UpdateCheckError", "Update check failed" },
        { "Settings_Title", "Settings" },
        { "Settings_Base", "Global" },
        { "Settings_Servers_Dir", "Servers Directory" },
        { "Settings_Servers_DirDesc", "Directory for server files" },
        { "Settings_Servers_Browse", "Browse" },
        { "Settings_Java", "Java" },
        { "Settings_Java_Empty", "No Java installed!" },
        { "Settings_Java_Add", "Add Java" },
        { "Settings_Java_Delete", "Delete" },
        { "Settings_Java_Delete_Confirm_Title", "Delete Java?" },
        { "Settings_Java_Delete_Confirm_Message", "Are you sure you want to delete the following Java installation?\n\n{0}" },
        { "Settings_Java_Delete_Failed", "Failed to delete Java" },
        { "Settings_Java_Scan", "Scan" },
        { "Settings_Java_Scanning", "Scanning..." },
        { "Settings_Java_Scan_Success", "Found {0} Java installation(s)" },
        { "Settings_Java_Scan_NoneFound", "No Java installations found" },
        { "Settings_Java_Scan_Error", "Error scanning for Java" },
        { "Settings_CheckUpdates", "Check for Updates" },
        { "Settings_CheckUpdates_Desc", "Automatically check for updates" },
        { "Settings_CheckUpdates_OnLaunch", "On Launch" },
        { "Settings_CheckUpdates_Scheduled", "Scheduled" },
        { "Settings_CheckUpdates_Interval", "Check interval" },
        { "Settings_CheckUpdates_Interval_Desc", "Update check frequency" },
        { "Settings_MinimizeToTray", "Minimize to Tray" },
        { "Settings_MinimizeToTray_Desc", "Minimize to tray on close or minimize" },
        { "Settings_MinimizeToTray_None", "Never" },
        { "Settings_MinimizeToTray_OnClose", "On Close" },
        { "Settings_MinimizeToTray_OnMinimize", "On Minimize" },
        { "Settings_MinimizeToTray_Always", "Always" },
        { "Settings_Appearance", "Appearance" },
        { "Settings_Theme", "Theme" },
        { "Settings_Theme_Desc", "Select app theme" },
        { "Settings_Theme_System", "System Default" },
        { "Settings_Theme_Dark", "Dark" },
        { "Settings_Theme_Light", "Light" },
        { "Settings_Language", "Language" },
        { "Settings_Language_Desc", "Select app language" },
        { "Settings_Language_System", "System Default" },
        { "Settings_Language_English", "English" },
        { "Settings_Language_Russian", "Russian" },
        { "Settings_About", "About" },
        { "Settings_About_Description", "Minecraft Server Manager" },
        { "Settings_About_ModalLoaders", "Supported Mod Loaders:" },
        { "Message_SettingsSaved", "Settings saved" },
        { "Validation_NameRequired", "Enter server name" },
        { "Validation_RamMinRequired", "Enter min RAM" },
        { "Validation_RamMaxRequired", "Enter max RAM" },
        { "Validation_AutoRestartDelayRequired", "Enter restart delay" },
        { "Validation_JvmArgsRequired", "Enter JVM arguments" },
        { "CreateServer_Title", "Create Server" },
        { "CreateServer_Name", "Server Name" },
        { "CreateServer_MinecraftVersion", "Minecraft Version" },
        { "CreateServer_ModLoader", "Mod Loader" },
        { "CreateServer_ModLoaderVersion", "Mod Loader Version" },
        { "CreateServer_Folder", "Folder" },
        { "CreateServer_Create", "Create" },
        { "CreateServer_Browse", "Browse" },
        { "CreateServer_Cancel", "Cancel" },
        { "CreateServer_Filter_Stable", "Show pre-releases" },
        { "CreateServer_Not_Found", "Not found" },
        { "CreateServer_Import", "Import" },
        { "CreateServer_Error_DialogLoad", "Error loading dialog" },
        { "CreateServer_Import_Duplicate", "A server from this folder is already imported:\n{0}" },
        { "CreateServer_Import_NoJar", "No server JAR file found in the selected folder." },
        { "CreateServer_Import_Success", "Server \"{0}\" imported successfully!" },
        { "CreateServer_Import_Success_Title", "Import Complete" },
        { "CreateServer_Import_Error", "Server import error" },
        { "CreateServer_Error_NoFolder", "Select a folder for the server" },
        { "CreateServer_Error_NoServerManager", "ServerManager is not initialized!" },
        { "CreateServer_Validation_NoName", "Enter a server name" },
        { "CreateServer_Validation_NoLoaderVersion", "Select a mod loader version" },
        { "CreateServer_Validation_NoFolder", "Select a server folder" },
        { "CreateServer_Error_DuplicateName", "A server named \"{0}\" already exists. Please choose a different name." },
        { "CreateServer_Error_CreateFailed", "Error creating server" },
        { "CreateServer_Error_InstallFailed", "Failed to install server" },
        { "CreateServer_Error_InstallFailed_Exception", "Error installing server" },
        { "CreateServer_Browse_Title", "Select server folder" },
        { "CreateServer_Import_Title", "Select server folder to import" },
        { "CreateServer_Installing_Preparing", "Preparing..." },
        { "CreateServer_Installing_Progress", "Installing {0}..." },
        { "CreateServer_Install_Error", "Error: {0}" },
        { "CreateServer_Install_Cancelled", "Cancelled" },
        { "CreateServer_Install_Ready", "Ready" },
        { "Installer_Downloading", "Downloading {0}..." },
        { "Installer_DownloadingServer", "Downloading server..." },
        { "Installer_CreatingConfig", "Creating configuration..." },
        { "Installer_Finishing", "Finishing..." },
        { "Installer_ChangingSource", "Changing source..." },
        { "Installer_DownloadingInstaller", "Downloading installer..." },
        { "Installer_RunningInstaller", "Installing {0}..." },
        { "Installer_Finalizing", "Finalizing..." },
        { "Installer_Extracting", "Extracting and downloading..." },
        { "Installer_ApplyingPatches", "Applying patches ({0}K)..." },
        { "Installer_Preparing", "Preparing..." },
        { "Installer_Configuring", "Configuring server..." },
        { "Installer_Installing", "Installing..." },
        { "Installer_Running", "Running installer..." },
        { "Installer_Success", "Installation complete!" },
        { "Installer_ShowLog", "Show log" },
        { "Installer_Log_Title", "Installation Log" },
        { "CreateServer_Validation_PathEmpty", "Server path cannot be empty" },
        { "CreateServer_Validation_InvalidChars", "Path contains invalid characters" },
        { "CreateServer_Validation_PathTooLong", "Path is too long (max {0} characters)" },
        { "CreateServer_Validation_FileNotFolder", "Specified path is a file, not a folder" },
        { "CreateServer_Validation_SystemFolder", "Cannot create servers in Windows system folders" },
        { "CreateServer_Validation_FolderNotEmpty", "Folder is not empty ({0} files). Make sure this is the right location for the server." },
        { "CreateServer_Validation_ParentNotFound", "Parent folder does not exist" },
        { "CreateServer_Validation_NoPermission", "Insufficient permissions to create folder" },
        { "CreateServer_Validation_Error", "Path validation error: {0}" },
        { "ServersPage_Search", "Search..." },
        { "ServersPage_Filter_All", "All Types" },
        { "ServersPage_Filter_AllServers", "All Servers" },
        { "ServersPage_Filter_Running", "Running" },
        { "ServersPage_Filter_Stopped", "Stopped" },
        { "ServersPage_SortBy", "Sort by" },
        { "ServersPage_Sort_Header", "Sort by" },
        { "ServersPage_Sort_Name", "Name" },
        { "ServersPage_Sort_Status", "Status" },
        { "ServersPage_Sort_Type", "Type" },
        { "ServersPage_Sort_Version", "Version" },
        { "ServersPage_Filter_Status", "Status" },
        { "ServersPage_Create", "Create Server" },
        { "ServersPage_Port", "Port:" },
        { "ServersPage_OpenFolder", "Open Server Folder" },
        { "ServersPage_Delete", "Delete Server" },
        { "ServersPage_NoServers", "No Servers" },
        { "ServersPage_NoServers_Description", "Create your first server to get started" },
        { "Common_Copied", "Copied!" },
        { "Common_None", "None" },
        { "MsgBtn_OK", "OK" },
        { "MsgBtn_Yes", "Yes" },
        { "MsgBtn_No", "No" },
        { "MsgBtn_Cancel", "Cancel" },
        { "MsgBtn_Delete", "Delete" },
        { "UiHelper_OpenFolderError", "Failed to open folder" },
        { "MsgTitle_Info", "Information" },
        { "MsgTitle_Warning", "Warning" },
        { "MsgTitle_Error", "Error" },
        { "MsgTitle_Confirm", "Confirm" },
        { "MsgDel_Title", "Delete Server" },
        { "MsgDel_Confirm", "Are you sure you want to delete server \"{0}\"?" },
        { "MsgDel_Irreversible", "This action is irreversible!" },
        { "MsgDelete_Title", "Confirm Deletion" },
        { "MsgDelete_Confirm", "Are you sure you want to delete \"{0}\"?" },
        { "ServerDetail_Console", "Console" },
        { "ServerDetail_Properties", "File server.properties" },
        { "ServerDetail_Settings", "Server Settings" },
        { "ServerDetail_Mods", "Mods" },
        { "ServerDetail_Plugins", "Plugins" },
        { "ServerDetail_Start", "Start" },
        { "ServerDetail_Stop", "Stop" },
        { "ServerDetail_StartStop", "Start/Stop" },
        { "ServerDetail_Starting", "Starting..." },
        { "ServerDetail_Stopping", "Stopping..." },
        { "ServerStatus_Error", "Error" },
        { "ServerDetail_Delete", "Delete" },
        { "ServerDetail_OpenFolder", "Open Folder" },
        { "ServerDetail_Java", "Java" },
        { "ServerDetail_Console_Empty", "Console is empty — start the server" },
        { "ServerDetail_SendCommand", "Send" },
        { "ServerDetail_Mods_List", "Mods List" },
        { "ServerDetail_Mods_OpenFolder", "Open mods folder" },
        { "ServerDetail_Mods_Refresh", "Refresh" },
        { "ServerDetail_Mods_Delete", "Delete" },
        { "ServerDetail_Mods_ToggleAll", "Toggle All" },
        { "ServerDetail_Mods_ToggleAll_Enable", "Enable All Mods" },
        { "ServerDetail_Mods_ToggleAll_Disable", "Disable All Mods" },
        { "ServerDetail_Plugins_List", "Plugins List" },
        { "ServerDetail_Plugins_OpenFolder", "Open plugins folder" },
        { "ServerDetail_Plugins_Refresh", "Refresh" },
        { "ServerDetail_Plugins_Delete", "Delete" },
        { "ServerDetail_Plugins_ToggleAll", "Toggle All" },
        { "ServerDetail_Plugins_ToggleAll_Enable", "Enable All Plugins" },
        { "ServerDetail_Plugins_ToggleAll_Disable", "Disable All Plugins" },
        { "ServerProperties_Save", "Save" },
        { "ServerProperties_FileNotCreated", "server.properties not yet created" },
        { "ServerProperties_FileNotCreated_Hint", "Auto-created on first server start" },
        { "ServerProperties_General", "General" },
        { "ServerProperties_ServerPort", "Server Port" },
        { "ServerProperties_ServerPort_Desc", "Game port (forward on router)" },
        { "ServerProperties_ServerIp", "Server IP" },
        { "ServerProperties_ServerIp_Desc", "Blank = all interfaces" },
        { "ServerProperties_MaxPlayers", "Max Players" },
        { "ServerProperties_MaxPlayers_Desc", "Maximum concurrent players" },
        { "ServerProperties_ViewDistance", "View Distance" },
        { "ServerProperties_ViewDistance_Desc", "Client chunk render distance" },
        { "ServerProperties_SimulationDistance", "Simulation Distance" },
        { "ServerProperties_SimulationDistance_Desc", "Entity and world update distance" },
        { "ServerProperties_Gamemode", "Game Mode" },
        { "ServerProperties_Gamemode_Desc", "Default game mode for new players" },
        { "ServerProperties_Gamemode_Survival", "Survival" },
        { "ServerProperties_Gamemode_Creative", "Creative" },
        { "ServerProperties_Gamemode_Adventure", "Adventure" },
        { "ServerProperties_Gamemode_Spectator", "Spectator" },
        { "ServerProperties_Difficulty", "Difficulty" },
        { "ServerProperties_Difficulty_Desc", "Mob damage, hunger, and survival mechanics" },
        { "ServerProperties_Difficulty_Peaceful", "Peaceful" },
        { "ServerProperties_Difficulty_Easy", "Easy" },
        { "ServerProperties_Difficulty_Normal", "Normal" },
        { "ServerProperties_Difficulty_Hard", "Hard" },
        { "ServerProperties_Hardcore", "Hardcore" },
        { "ServerProperties_Hardcore_Desc", "Permanent death (cannot disable on running server)" },
        { "ServerProperties_PvP", "PvP" },
        { "ServerProperties_PvP_Desc", "Allow player-to-player combat" },
        { "ServerProperties_CommandBlocks", "Command Blocks" },
        { "ServerProperties_CommandBlocks_Desc", "Enable command blocks" },
        { "ServerProperties_World", "World" },
        { "ServerProperties_LevelName", "Level Name" },
        { "ServerProperties_LevelName_Desc", "World save folder name" },
        { "ServerProperties_LevelSeed", "Level Seed" },
        { "ServerProperties_LevelSeed_Desc", "World seed (blank = random)" },
        { "ServerProperties_LevelType", "Level Type" },
        { "ServerProperties_LevelType_Desc", "Terrain generation type" },
        { "ServerProperties_LevelType_Normal", "Normal" },
        { "ServerProperties_LevelType_Flat", "Flat" },
        { "ServerProperties_LevelType_LargeBiomes", "Large Biomes" },
        { "ServerProperties_LevelType_Amplified", "Amplified" },
        { "ServerProperties_LevelType_SingleBiome", "Single Biome" },
        { "ServerProperties_MaxWorldSize", "Max World Size" },
        { "ServerProperties_MaxWorldSize_Desc", "World radius limit in blocks" },
        { "ServerProperties_SpawnStructures", "Spawn Structures" },
        { "ServerProperties_SpawnStructures_Desc", "Villages, temples, strongholds, etc." },
        { "ServerProperties_AllowNether", "Allow Nether" },
        { "ServerProperties_AllowNether_Desc", "Allow Nether portal access" },
        { "ServerProperties_Network", "Network" },
        { "ServerProperties_OnlineMode", "Online Mode" },
        { "ServerProperties_OnlineMode_Desc", "Disable for cracked clients" },
        { "ServerProperties_Whitelist", "Whitelist" },
        { "ServerProperties_Whitelist_Desc", "Only whitelisted players can join" },
        { "ServerProperties_EnforceWhitelist", "Enforce Whitelist" },
        { "ServerProperties_EnforceWhitelist_Desc", "Kick players removed from whitelist" },
        { "ServerProperties_EnforceSecureProfile", "Enforce Secure Profile" },
        { "ServerProperties_EnforceSecureProfile_Desc", "Require signed client profile" },
        { "ServerProperties_AllowFlight", "Allow Flight" },
        { "ServerProperties_AllowFlight_Desc", "Allow flight (enable for flight mods)" },
        { "ServerProperties_RCON", "RCON" },
        { "ServerProperties_EnableRcon", "Enable RCON" },
        { "ServerProperties_EnableRcon_Desc", "Remote server management over network" },
        { "ServerProperties_RconPassword", "RCON Password" },
        { "ServerProperties_RconPassword_Desc", "Password for RCON connection" },
        { "ServerProperties_RconPort", "RCON Port" },
        { "ServerProperties_RconPort_Desc", "Port for RCON connections" },
        { "ServerProperties_Permissions", "Permissions" },
        { "ServerProperties_SpawnProtection", "Spawn Protection" },
        { "ServerProperties_SpawnProtection_Desc", "Spawn protection radius (0 = off)" },
        { "ServerProperties_SpawnRadius", "Spawn Radius" },
        { "ServerProperties_SpawnRadius_Desc", "Player spawn offset from spawn point" },
        { "ServerProperties_OpPermissionLevel", "OP Permission Level" },
        { "ServerProperties_OpPermissionLevel_Desc", "Max operator access level (1-4)" },
        { "ServerProperties_MaxTickTime", "Max Tick Time" },
        { "ServerProperties_MaxTickTime_Desc", "Max tick time in ms (-1 = disabled)" },
        { "ServerProperties_NetworkCompression", "Network Compression" },
        { "ServerProperties_NetworkCompression_Desc", "Packet compression threshold" },
        { "ServerProperties_SpawnNPCs", "Spawn NPCs" },
        { "ServerProperties_SpawnNPCs_Desc", "NPC spawning (villagers)" },
        { "ServerProperties_SpawnAnimals", "Spawn Animals" },
        { "ServerProperties_SpawnAnimals_Desc", "Animal spawning (cows, pigs, etc.)" },
        { "ServerProperties_SpawnMonsters", "Spawn Monsters" },
        { "ServerProperties_SpawnMonsters_Desc", "Monster spawning (zombies, creepers, etc.)" },
        { "ServerProperties_EnabledPacks", "Enabled Datapacks" },
        { "ServerProperties_EnabledPacks_Desc", "Enabled datapacks (comma-separated)" },
        { "ServerProperties_DisabledPacks", "Disabled Datapacks" },
        { "ServerProperties_DisabledPacks_Desc", "Disabled datapacks (comma-separated)" },
        { "ServerProperties_Reset", "Reset" },
        { "ServerProperties_Refresh", "Refresh" },
        { "ServerProperties_Performance", "Performance" },
        { "ServerProperties_ForceGamemode", "Force Gamemode" },
        { "ServerProperties_ForceGamemode_Desc", "Force server gamemode on players" },
        { "ServerProperties_GeneratorSettings", "Generator Settings" },
        { "ServerProperties_GeneratorSettings_Desc", "World generation parameters (JSON)" },
        { "ServerProperties_PreventProxyConnections", "Block Proxies" },
        { "ServerProperties_PreventProxyConnections_Desc", "Block proxy connections" },
        { "ServerProperties_RateLimit", "Rate Limit" },
        { "ServerProperties_RateLimit_Desc", "Max packets/second (0 = unlimited)" },
        { "ServerProperties_PlayerIdleTimeout", "Idle Timeout" },
        { "ServerProperties_PlayerIdleTimeout_Desc", "Kick after X min idle (0 = off)" },
        { "ServerProperties_AcceptsTransfers", "Accept Transfers" },
        { "ServerProperties_AcceptsTransfers_Desc", "Accept world transfers from other servers" },
        { "ServerProperties_StatusHeartbeatInterval", "Heartbeat Interval" },
        { "ServerProperties_StatusHeartbeatInterval_Desc", "Status report interval (0 = default)" },
        { "ServerProperties_HideOnlinePlayers", "Hide Players" },
        { "ServerProperties_HideOnlinePlayers_Desc", "Hide players from server status" },
        { "ServerProperties_WhitelistSection", "Whitelist" },
        { "ServerProperties_Query", "Query" },
        { "ServerProperties_EnableQuery", "Enable Query" },
        { "ServerProperties_EnableQuery_Desc", "GameSpy 4 query protocol" },
        { "ServerProperties_QueryPort", "Query Port" },
        { "ServerProperties_QueryPort_Desc", "Port for Query requests" },
        { "ServerProperties_FunctionPermissionLevel", "Function Permission Level" },
        { "ServerProperties_FunctionPermissionLevel_Desc", "Max permission level for functions (1-4)" },
        { "ServerProperties_ManagementServer", "Management Server" },
        { "ServerProperties_ManagementServerEnabled", "Enable Management Server" },
        { "ServerProperties_ManagementServerEnabled_Desc", "Enable management API" },
        { "ServerProperties_ManagementServerHost", "Management Host" },
        { "ServerProperties_ManagementServerHost_Desc", "Management API bind address" },
        { "ServerProperties_ManagementServerPort", "Management Port" },
        { "ServerProperties_ManagementServerPort_Desc", "Management API port" },
        { "ServerProperties_ManagementServerSecret", "Management Secret" },
        { "ServerProperties_ManagementServerSecret_Desc", "API secret key" },
        { "ServerProperties_ManagementServerTlsEnabled", "Management TLS" },
        { "ServerProperties_ManagementServerTlsEnabled_Desc", "Enable TLS for API" },
        { "ServerProperties_ManagementServerTlsKeystore", "TLS Keystore" },
        { "ServerProperties_ManagementServerTlsKeystore_Desc", "Path to keystore file" },
        { "ServerProperties_ManagementServerAllowedOrigins", "Allowed Origins" },
        { "ServerProperties_ManagementServerAllowedOrigins_Desc", "Allowed CORS origins" },
        { "ServerProperties_ResourcePack", "Resource Pack" },
        { "ServerProperties_ResourcePackUrl", "Resource Pack URL" },
        { "ServerProperties_ResourcePackUrl_Desc", "Resource pack download URL" },
        { "ServerProperties_ResourcePackSha1", "Resource Pack SHA1" },
        { "ServerProperties_ResourcePackSha1_Desc", "Resource pack SHA1 hash" },
        { "ServerProperties_ResourcePackId", "Resource Pack ID" },
        { "ServerProperties_ResourcePackId_Desc", "Resource pack identifier" },
        { "ServerProperties_ResourcePackPrompt", "Resource Pack Prompt" },
        { "ServerProperties_ResourcePackPrompt_Desc", "Prompt text for resource pack request" },
        { "ServerProperties_RequireResourcePack", "Require Resource Pack" },
        { "ServerProperties_RequireResourcePack_Desc", "Force resource pack download" },
        { "ServerProperties_MaxChainedNeighborUpdates", "Chained Neighbor Updates" },
        { "ServerProperties_MaxChainedNeighborUpdates_Desc", "Max chained neighbor updates (-1 = unlimited)" },
        { "ServerProperties_EntityBroadcastRangePercentage", "Entity Range" },
        { "ServerProperties_EntityBroadcastRangePercentage_Desc", "Entity broadcast range %" },
        { "ServerProperties_SyncChunkWrites", "Sync Chunk Writes" },
        { "ServerProperties_SyncChunkWrites_Desc", "Synchronize chunk writes" },
        { "ServerProperties_UseNativeTransport", "Native Transport" },
        { "ServerProperties_UseNativeTransport_Desc", "Native Linux transport" },
        { "ServerProperties_Logging", "Logging" },
        { "ServerProperties_LogIps", "Log IPs" },
        { "ServerProperties_LogIps_Desc", "Log IP addresses" },
        { "ServerProperties_BroadcastConsoleToOps", "Console → OPS" },
        { "ServerProperties_BroadcastConsoleToOps_Desc", "Forward console to operators" },
        { "ServerProperties_BroadcastRconToOps", "RCON → OPS" },
        { "ServerProperties_BroadcastRconToOps_Desc", "Forward RCON to operators" },
        { "ServerProperties_EnableJmxMonitoring", "JMX Monitoring" },
        { "ServerProperties_EnableJmxMonitoring_Desc", "Enable JMX monitoring" },
        { "ServerProperties_EnableCodeOfConduct", "Code of Conduct" },
        { "ServerProperties_EnableCodeOfConduct_Desc", "Enforce code of conduct" },
        { "ServerProperties_BugReportLink", "Bug Report Link" },
        { "ServerProperties_BugReportLink_Desc", "URL for bug reports" },
        { "ServerProperties_PauseWhenEmptySeconds", "Pause When Empty" },
        { "ServerProperties_PauseWhenEmptySeconds_Desc", "Pause ticks when no players are online" },
        { "ServerProperties_RegionFileCompression", "Region File Compression" },
        { "ServerProperties_RegionFileCompression_Desc", "World file compression algorithm" },
        { "ServerProperties_RegionFileCompression_Deflate", "Deflate (Zlib)" },
        { "ServerProperties_RegionFileCompression_Lz4", "LZ4" },
        { "ServerProperties_TextFilteringConfig", "Text Filtering Config" },
        { "ServerProperties_TextFilteringConfig_Desc", "Path to text filter config" },
        { "ServerProperties_TextFilteringVersion", "Text Filtering Version" },
        { "ServerProperties_TextFilteringVersion_Desc", "Filter version for config updates" },
        { "ServerProperties_ManagementServerTlsKeystorePassword", "TLS Keystore Password" },
        { "ServerProperties_ManagementServerTlsKeystorePassword_Desc", "Password for TLS keystore" },
        { "ServerDetail_Settings_General", "Server name" },
        { "ServerDetail_Settings_General_Desc", "Server name in the app" },
        { "ServerDetail_Settings_RAM", "Memory Allocation" },
        { "ServerDetail_Settings_RAM_Min", "Min RAM (MB)" },
        { "ServerDetail_Settings_RAM_Min_Desc", "Minimum memory for server" },
        { "ServerDetail_Settings_RAM_Max", "Max RAM (MB)" },
        { "ServerDetail_Settings_RAM_Max_Desc", "Maximum memory for server" },
        { "ServerDetail_Settings_AutoRestart", "Auto-Restart" },
        { "ServerDetail_Settings_AutoRestart_Enable", "Enable auto-restart" },
        { "ServerDetail_Settings_AutoRestart_Desc", "Auto-restart server on stop" },
        { "ServerDetail_Settings_AutoRestart_Delay", "Restart delay (sec)" },
        { "ServerDetail_Settings_AutoRestart_Delay_Desc", "Delay before auto-restart" },
        { "ServerDetail_Settings_Java_Auto", "Auto-select Java version" },
        { "ServerDetail_Settings_Java_Auto_Desc", "Auto-select Java from Minecraft version" },
        { "ServerDetail_Settings_Java_Version", "Java Version" },
        { "ServerDetail_Settings_JvmArgs", "JVM Arguments" },
        { "ServerDetail_Settings_JvmArgs_Desc", "One argument per line" },
        { "Log_ServerStarted", "Server fully loaded" },
        { "Log_JavaVersionMismatch", "JAVA VERSION MISMATCH!" },
        { "Log_JavaVersionMismatch_Detail", "Minecraft {0} requires Java {1} or higher" },
        { "Log_JavaFound", "Found Java: {0} (version {1})" },
        { "Log_JavaPath", "Java path: {0}" },
        { "Log_Solution", "Solution:" },
        { "Log_Solution_Install_Java", "1. Install Java {0}: https://adoptium.net/" },
        { "Log_Solution_Add_Java", "2. Specify Java {0} path in application settings" },
        { "Log_Solution_Older_Minecraft", "3. Or select an older Minecraft version" },
        { "Log_JavaNotFound", "JAVA NOT FOUND!" },
        { "Log_JavaNotFound_Path", "Java path: {0}" },
        { "Log_JavaNotFound_Error", "Error: {0}" },
        { "Log_Solution_Install_Java_General", "1. Install Java: https://adoptium.net/" },
        { "Log_Solution_Add_Java_Settings", "2. Add Java in application settings ('Add Java' button)" },
        { "Log_Solution_Check_PATH", "3. Make sure Java is added to PATH" },
        { "Log_CriticalError", "Critical startup error!" },
        { "Log_ErrorType", "Type: {0}" },
        { "Log_ErrorMessage", "Message: {0}" },
        { "Log_ErrorOutput", "Error output: {0}" },
        { "Log_ServerStoppedWithCode", "Server exited with error code: {0}" },
        { "Log_ServerConfigProblem", "This may indicate a configuration problem" },
        { "Log_MemoryProblem", "or insufficient memory." },
        { "Log_TimeoutForceKill", "Stop timeout, force killing..." },
        { "Log_ForceKillAttempt", "Attempting force kill..." },
        { "Log_ServerNotRunning", "Attempting to send command to stopped server: {0}" },
        { "Log_JavaFromSettingsNotFound", "Java from server settings not found: {0}" },
        { "Log_JavaVersionNotFound_TryDefault", "Java {0}+ not found, trying default Java" },
        { "Log_JavaDefaultNotFound", "Default Java not found: {0}" },
        { "Log_JarFile", "JAR File: {0} ({1} MB)" },
        { "Log_JavaArgs", "Java Arguments: {0}" },
        { "Log_LaunchingProcess", "Launching process..." },
        { "Log_WaitingForStartup", "Waiting for server startup..." },
        { "Log_LaunchCancelled", "Launch cancelled" },
        { "Log_EulaAccepted", "EULA accepted" },
        { "Log_ProcessStarted", "Process started, PID: {0}" },
        { "Log_LaunchForceCancelled", "Launch force cancelled" },
        { "Log_ProcessForceKilled", "Process force killed (server not yet loaded)" },
        { "Log_ExitError", "Exit error: {0}" },
        { "Log_ProcessForceKilledAfterTimeout", "Process force killed after timeout" },
        { "Log_ServerStoppedSuccessfully", "Server stopped successfully" },
        { "Log_StopCancelled", "Stop cancelled" },
        { "Log_KillFailedOnCancel", "Failed to kill process on cancel: {0}" },
        { "Log_StopError", "Stop error: {0}" },
        { "Log_CommandSent", "> {0}" },
        { "Log_CommandSendError", "Failed to send command '{0}': {1}" },
        { "Log_ConfigUnavailable", "Config unavailable, using Java from PATH" },
        { "Log_AutoRestart", "Auto-restart in" },
        { "Log_Seconds", "sec" },
        { "Log_ServerStarting", "Starting server: {0}" },
        { "Log_KillFailed", "Failed to kill process: {0}" },
        { "Log_MonitorCancelled", "Process monitoring cancelled" },
        { "Log_MonitorError", "Process monitoring error: {0}" },
        { "Snackbar_JavaIncompatible_Title", "Incompatible Java" },
        { "Snackbar_JavaIncompatible_Message", "Minecraft {0} requires Java {1}+, found Java {2}.\nThe server will not start with the current Java version." },
        { "Snackbar_JavaIncompatible_Message_Plural", "Minecraft {0} requires Java {1}+, found Java: {2}.\nThe server will not start with the current Java versions." },
        { "Common_NotSelected", "Not selected" },
        { "Common_Unknown", "Unknown" },
        { "Common_Preparing", "Preparing..." },
        { "Common_Close", "Close" },
        { "Common_Copy", "Copy" },
        { "Settings_SelectServerFolder", "Select servers folder" },
        { "Settings_SelectJava", "Select java.exe or javaw.exe" },
        { "Settings_JavaFilter", "Java executable|java.exe|JavaW executable|javaw.exe" },
        { "Settings_JavaAdded", "Java added" },
        { "Settings_JavaVersion", "Version" },
        { "Settings_JavaPath", "Path" },
        { "Settings_JavaInvalid", "Failed to add Java. Check the file path.\n\nMake sure the selected file is java.exe or javaw.exe" },
        { "Props_Loaded", "Properties loaded" },
        { "Props_NotLoaded", "Error: file not loaded" },
        { "Props_Saved", "Properties saved!" },
        { "Props_SaveError", "Save error" },
        { "Props_Reset", "Properties reset" },
        { "ServerDetail_OperationError", "Failed to perform operation" },
        { "ServerDetail_PropsLoadError", "Error loading properties" },
        { "ServerDetail_ModsFolderNotFound", "Mods folder not found" },
        { "ServerDetail_PluginsFolderNotFound", "Plugins folder not found" },
        { "ServerDetail_DeleteModConfirm", "Delete mod \"{0}\"?\n\nFile: {1}" },
        { "ServerDetail_DeleteModTitle", "Delete Mod" },
        { "ServerDetail_DeletePluginConfirm", "Delete plugin \"{0}\"?\n\nFile: {1}" },
        { "ServerDetail_DeletePluginTitle", "Delete Plugin" },
        { "ServerDetail_ModDeleteError", "Error deleting mod" },
        { "ServerDetail_ModToggleError", "Failed to toggle mod" },
        { "ServerDetail_PluginDeleteError", "Error deleting plugin" },
        { "ServerDetail_PluginToggleError", "Failed to toggle plugin" },
        { "ServerDetail_DeleteServerError", "Error deleting server" },
        { "ServerDetail_JavaDefault", "Default" },
        { "ServerDetail_JavaNotSelected", "not selected" },
        { "App_StartupError", "Application initialization error" },
        { "App_StartupErrorDetail", "Check logs in %AppData%\\Konserva\\Logs" },
        { "App_UnhandledError", "Unhandled exception" },
        { "App_UnhandledErrorDetail", "Application will be closed." },
        { "Settings_Download", "Downloads" },
        { "Settings_DownloadSource", "Download Source" },
        { "Settings_DownloadSource_Desc", "Modloader and game file source" },
        { "Settings_DownloadSource_VanillaApi", "Official Minecraft API" },
        { "Settings_DownloadSource_BMCLAPI", "BMCLAPI (mirror, faster in China/Russia)" },
        { "ServerDetail_Upnp", "UPnP Port Forwarding" },
        { "ServerDetail_Upnp_Enable", "Auto Forward Port (UPnP)" },
        { "ServerDetail_Upnp_Enable_Desc", "Open server port via UPnP on start" },
        { "ServerDetail_Upnp_Check", "Check UPnP" },
        { "ServerDetail_Upnp_Checking", "Checking..." },
        { "ServerDetail_Upnp_Available", "UPnP is available ✓" },
        { "ServerDetail_Upnp_NotAvailable", "UPnP not available (disabled on router?)" },
        { "ServerDetail_Upnp_CheckPort", "Check Port" },
        { "ServerDetail_Upnp_Port_Open", "Port Open" },
        { "ServerDetail_Upnp_Port_Closed", "Port Closed" },
        { "ServerDetail_Upnp_CopyAddress", "Copy" },
        { "ServerDetail_Settings_RunningWarning", "Some settings cannot be changed while the server is running" },
        { "ServerDetail_Settings_RenameError", "Failed to rename server folder: {0}" },
        { "ServerDetail_Settings_RenameSuccess", "Server folder renamed to \"{0}\"" },
        { "Log_JavaTooNewWarning", "Java {0} (v{1}) is much newer than required ({2}+). The server may not work correctly. Consider installing Java {2} or {2}+4." },
        { "Log_JavaClassFileVersionError", "Java {0} (v{1}) is too new for this server. The Forge version used here was compiled for Java 17.\nTry installing Java 17 or 21 and restarting the server." },
        { "Log_ServerReady", "Server started successfully" },
        { "Log_ServerReady_Commands", "Use the console below to send commands" }
    };
}
