using System.Collections.Generic;

namespace Konserva.Localization;

public static class EnglishStrings
{
    public static readonly Dictionary<string, string> Translations = new Dictionary<string, string>
    {
        { "MainWindow_Title", "Konserva — Minecraft Server Manager" },
        { "MainWindow_Servers", "Servers" },
        { "MainWindow_Settings", "Settings" },
        { "MainWindow_Header", "Konserva Manager" },
        { "StatusBar_TotalServers", "Total Servers" },
        { "StatusBar_Running", "Running" },
        { "StatusBar_Memory", "Memory" },
        { "StatusBar_Java_Configured", "Java configured" },
        { "StatusBar_Java_NotConfigured", "Java not configured" },
        { "StatusBar_Version", "Version" },
        { "MainWindow_JavaVersions", "Java versions" },
        { "MainWindow_Error", "Error" },
        { "Update_Available", "v{0} available" },
        { "Update_Button", "Update" },
        { "Update_Downloading", "Downloading..." },
        { "Update_Installing", "Installing..." },
        { "Update_Success", "Restarting..." },
        { "Update_Failed", "Update failed" },
        { "Update_Retry", "Retry" },
        { "Update_Available_Tooltip", "Click to update" },
        { "Update_Failed_Tooltip", "Update failed. Click to retry." },
        { "Settings_CheckForUpdates", "Check for Updates" },
        { "Settings_UpToDate", "Up to date" },
        { "Settings_UpToDate_Button", "Up to Date" },
        { "Settings_UpdateAvailable_Button", "Update Available {0}" },
        { "Settings_UpdateCheckError", "Update check failed" },
        { "Settings_Title", "Settings" },
        { "Settings_Servers", "Servers" },
        { "Settings_Servers_Dir", "Servers Directory" },
        { "Settings_Servers_DirDesc", "Directory for saving server" },
        { "Settings_Servers_Browse", "Browse" },
        { "Settings_Java", "Java" },
        { "Settings_Java_Empty", "No Java installed!" },
        { "Settings_Java_Add", "Add Java" },
        { "Settings_Java_Delete", "Delete" },
        { "Settings_Java_Delete_Confirm_Title", "Delete Java?" },
        { "Settings_Java_Delete_Confirm_Message", "Are you sure you want to remove this Java installation?" },
        { "Settings_Java_Delete_Failed", "Failed to delete Java" },
        { "Settings_RAM_Min", "Memory and Application" },
        { "Settings_RAM_Min_Label", "Min RAM (MB)" },
        { "Settings_RAM_Max_Label", "Max RAM (MB)" },
        { "Settings_RAM_Min_Desc", "Initial memory amount" },
        { "Settings_RAM_Max_Desc", "Maximum memory amount" },
        { "Settings_App", "Application" },
        { "Settings_CheckUpdates", "Check for Updates" },
        { "Settings_CheckUpdates_Desc", "Automatically check for updates" },
        { "Settings_CheckUpdates_Interval", "Check interval (hours)" },
        { "Settings_CheckUpdates_Interval_Desc", "How often to check for updates (1–168 hours)" },
        { "Settings_MinimizeToTray", "Minimize to Tray" },
        { "Settings_MinimizeToTray_Desc", "Minimize to system tray when closing the window instead of exiting" },
        { "Settings_ShowTrayIcon", "Show Tray Icon" },
        { "Settings_ShowTrayIcon_Desc", "Always show tray icon even when window is open. If disabled, icon appears only when minimized" },
        { "Settings_Appearance", "Appearance" },
        { "Settings_Theme", "Theme" },
        { "Settings_Theme_Desc", "Select application theme" },
        { "Settings_Theme_System", "System Default" },
        { "Settings_Theme_Dark", "Dark" },
        { "Settings_Theme_Light", "Light" },
        { "Settings_Language", "Language" },
        { "Settings_Language_Desc", "Select application language" },
        { "Settings_Language_System", "System Default" },
        { "Settings_Language_System_Auto", "(auto)" },
        { "Settings_Language_English", "English" },
        { "Settings_Language_Russian", "Russian" },
        { "Settings_About", "About" },
        { "Settings_About_Version", "Version" },
        { "Settings_About_Description", "Minecraft Server Manager" },
        { "Settings_About_ModalLoaders", "Supported Mod Loaders:" },
        { "Settings_About_InDevelopment", "In Development" },
        { "Message_SettingsSaved", "Settings saved" },
        { "CreateServer_Title", "Create Server" },
        { "CreateServer_Name", "Server Name" },
        { "CreateServer_MinecraftVersion", "Minecraft Version" },
        { "CreateServer_ModLoader", "Mod Loader" },
        { "CreateServer_ModLoaderVersion", "Mod Loader Version" },
        { "CreateServer_Folder", "Folder" },
        { "CreateServer_browse", "Browse" },
        { "CreateServer_Create", "Create" },
        { "CreateServer_Browse", "Browse" },
        { "CreateServer_Cancel", "Cancel" },
        { "CreateServer_Filter_Stable", "Show pre-releases" },
        { "CreateServer_Not_Found", "Not found" },
        { "CreateServer_Import", "Import" },
        { "CreateServer_Error_DialogLoad", "Error loading dialog" },
        { "CreateServer_Import_Duplicate", "A server from this folder is already imported:\n{0}" },
        { "CreateServer_Import_NoJar", "No server JAR file found in the selected folder." },
        { "CreateServer_Import_Success", "Server \"{0}\" imported successfully!" },
        { "CreateServer_Import_Success_Title", "Import Complete" },
        { "CreateServer_Import_Error", "Server import error" },
        { "CreateServer_Error_NoName", "Enter a server name" },
        { "CreateServer_Error_NoFolder", "Select a folder for the server" },
        { "CreateServer_Error_NoServerManager", "ServerManager is not initialized!" },
        { "CreateServer_Validation_NoName", "Enter a server name" },
        { "CreateServer_Validation_NoLoaderVersion", "Select a mod loader version" },
        { "CreateServer_Validation_NoFolder", "Select a server folder" },
        { "CreateServer_Error_DuplicateName", "A server named \"{0}\" already exists. Please choose a different name." },
        { "CreateServer_Error_CreateFailed", "Error creating server" },
        { "CreateServer_Error_InstallFailed", "Failed to install server" },
        { "CreateServer_Error_InstallFailed_Exception", "Error installing server" },
        { "ServersPage_Search", "Search..." },
        { "ServersPage_Filter_All", "All Types" },
        { "ServersPage_Filter_AllServers", "All Servers" },
        { "ServersPage_Filter_Running", "Running" },
        { "ServersPage_Filter_Stopped", "Stopped" },
        { "ServersPage_Create", "Create Server" },
        { "ServersPage_Port", "Port:" },
        { "ServersPage_OpenFolder", "Open Server Folder" },
        { "ServersPage_Delete", "Delete Server" },
        { "ServersPage_NoServers", "No Servers" },
        { "ServersPage_NoServers_Description", "Create your first server to get started" },
        { "ServersPage_Error_AppNotInitialized", "Error: Application not initialized" },
        { "Common_Cancel", "Cancel" },
        { "Common_OK", "OK" },
        { "Common_Yes", "Yes" },
        { "Common_No", "No" },
        { "Common_Loading", "Loading..." },
        { "Common_None", "None" },
        { "Common_InDevelopment", "In Development" },
        { "MsgBtn_OK", "OK" },
        { "MsgBtn_Yes", "Yes" },
        { "MsgBtn_No", "No" },
        { "MsgBtn_Cancel", "Cancel" },
        { "MsgBtn_Delete", "Delete" },
        { "UiHelper_OpenFolderError", "Failed to open folder" },
        { "MsgTitle_Info", "Information" },
        { "MsgTitle_Warning", "Warning" },
        { "MsgTitle_Error", "Error" },
        { "MsgTitle_Confirm", "Confirm" },
        { "MsgTitle_DeleteServer", "Delete Server" },
        { "MsgInfo_Title", "Information" },
        { "MsgWarning_Title", "Warning" },
        { "MsgError_Title", "Error" },
        { "MsgConfirm_Title", "Confirm" },
        { "MsgDel_Title", "Delete Server" },
        { "MsgDel_Confirm", "Are you sure you want to delete server \"{0}\"?" },
        { "MsgDel_WillBeDeleted", "The following will be deleted:" },
        { "MsgDel_ServerFiles", "All server files" },
        { "MsgDel_ConfigFiles", "Configuration files" },
        { "MsgDel_WorldSaves", "World and saves" },
        { "MsgDel_LogsBackups", "Logs and backups" },
        { "MsgDel_Irreversible", "This action is irreversible!" },
        { "ServerDetail_Title", "Server Details" },
        { "ServerDetail_Console", "Console" },
        { "ServerDetail_Properties", "File server.properties" },
        { "ServerDetail_Settings", "Server Settings" },
        { "ServerDetail_Mods", "Mods" },
        { "ServerDetail_Plugins", "Plugins" },
        { "ServerDetail_Start", "Start" },
        { "ServerDetail_Stop", "Stop" },
        { "ServerDetail_StartStop", "Start/Stop" },
        { "ServerDetail_Starting", "Starting..." },
        { "ServerDetail_Stopping", "Stopping..." },
        { "ServerDetail_Delete", "Delete" },
        { "ServerDetail_OpenFolder", "Open Folder" },
        { "ServerDetail_autoRestart", "Auto-Restart" },
        { "ServerDetail_Java", "Java" },
        { "ServerDetail_RAM", "RAM" },
        { "ServerDetail_Port", "Port" },
        { "ServerDetail_Name", "Name" },
        { "ServerDetail_Version", "Version" },
        { "ServerDetail_ModLoader", "Mod Loader" },
        { "ServerDetail_Status", "Status" },
        { "ServerDetail_Status_Running", "Running" },
        { "ServerDetail_Status_Stopped", "Stopped" },
        { "ServerDetail_Console_Empty", "Console is empty, start the server" },
        { "ServerDetail_SendCommand", "Send" },
        { "ServerDetail_Mods_List", "Installed Mods List" },
        { "ServerDetail_Mods_OpenFolder", "Open mods folder" },
        { "ServerDetail_Mods_Refresh", "Refresh" },
        { "ServerDetail_Mods_Delete", "Delete" },
        { "ServerDetail_Plugins_List", "Installed Plugins List" },
        { "ServerDetail_Plugins_OpenFolder", "Open plugins folder" },
        { "ServerDetail_Plugins_Refresh", "Refresh" },
        { "ServerDetail_Plugins_Delete", "Delete" },
        { "ServerProperties_Title", "Server Properties" },
        { "ServerProperties_Save", "Save" },
        { "ServerProperties_Cancel", "Cancel" },
        { "ServerProperties_FileNotCreated", "server.properties file not created yet" },
        { "ServerProperties_FileNotCreated_Hint", "File will be created automatically when the server starts for the first time" },
        { "ServerProperties_General", "General" },
        { "ServerProperties_ServerPort", "Server Port" },
        { "ServerProperties_ServerPort_Desc", "Connection port. Forward it on your router" },
        { "ServerProperties_ServerIp", "Server IP" },
        { "ServerProperties_ServerIp_Desc", "Leave blank to bind to all network interfaces" },
        { "ServerProperties_MaxPlayers", "Max Players" },
        { "ServerProperties_MaxPlayers_Desc", "How many players can be on the server at once" },
        { "ServerProperties_ViewDistance", "View Distance" },
        { "ServerProperties_ViewDistance_Desc", "How many chunks clients can see" },
        { "ServerProperties_SimulationDistance", "Simulation Distance" },
        { "ServerProperties_SimulationDistance_Desc", "How far mobs and world processes update" },
        { "ServerProperties_MOTD", "MOTD" },
        { "ServerProperties_MOTD_Desc", "Text players see in the server list" },
        { "ServerProperties_Gamemode", "Game Mode" },
        { "ServerProperties_Gamemode_Desc", "Default game mode for new players" },
        { "ServerProperties_Gamemode_Survival", "Survival" },
        { "ServerProperties_Gamemode_Creative", "Creative" },
        { "ServerProperties_Gamemode_Adventure", "Adventure" },
        { "ServerProperties_Gamemode_Spectator", "Spectator" },
        { "ServerProperties_Difficulty", "Difficulty" },
        { "ServerProperties_Difficulty_Desc", "Mob damage, hunger, and other survival mechanics" },
        { "ServerProperties_Difficulty_Peaceful", "Peaceful" },
        { "ServerProperties_Difficulty_Easy", "Easy" },
        { "ServerProperties_Difficulty_Normal", "Normal" },
        { "ServerProperties_Difficulty_Hard", "Hard" },
        { "ServerProperties_Hardcore", "Hardcore" },
        { "ServerProperties_Hardcore_Desc", "Death is permanent. Cannot be disabled on a running server" },
        { "ServerProperties_PvP", "PvP" },
        { "ServerProperties_PvP_Desc", "Whether players can attack each other" },
        { "ServerProperties_CommandBlocks", "Command Blocks" },
        { "ServerProperties_CommandBlocks_Desc", "Enables command blocks in the world" },
        { "ServerProperties_World", "World" },
        { "ServerProperties_LevelName", "Level Name" },
        { "ServerProperties_LevelName_Desc", "Name of the world save folder" },
        { "ServerProperties_LevelSeed", "Level Seed" },
        { "ServerProperties_LevelSeed_Desc", "World generation code. Leave blank for random" },
        { "ServerProperties_LevelType", "Level Type" },
        { "ServerProperties_LevelType_Desc", "Landscape generation type" },
        { "ServerProperties_LevelType_Normal", "Normal" },
        { "ServerProperties_LevelType_Flat", "Flat" },
        { "ServerProperties_LevelType_LargeBiomes", "Large Biomes" },
        { "ServerProperties_LevelType_Amplified", "Amplified" },
        { "ServerProperties_LevelType_SingleBiome", "Single Biome" },
        { "ServerProperties_MaxWorldSize", "Max World Size" },
        { "ServerProperties_MaxWorldSize_Desc", "Maximum world radius in blocks" },
        { "ServerProperties_SpawnStructures", "Spawn Structures" },
        { "ServerProperties_SpawnStructures_Desc", "Villages, temples, strongholds, and other world builds" },
        { "ServerProperties_AllowNether", "Allow Nether" },
        { "ServerProperties_AllowNether_Desc", "Allow Nether portal" },
        { "ServerProperties_Network", "Network" },
        { "ServerProperties_OnlineMode", "Online Mode" },
        { "ServerProperties_OnlineMode_Desc", "Disable for cracked clients" },
        { "ServerProperties_Whitelist", "Whitelist" },
        { "ServerProperties_Whitelist_Desc", "Only players on the list can join the server" },
        { "ServerProperties_EnforceWhitelist", "Enforce Whitelist" },
        { "ServerProperties_EnforceWhitelist_Desc", "Kick players removed from the whitelist" },
        { "ServerProperties_EnforceSecureProfile", "Enforce Secure Profile" },
        { "ServerProperties_EnforceSecureProfile_Desc", "Require signed profile from clients" },
        { "ServerProperties_AllowFlight", "Allow Flight" },
        { "ServerProperties_AllowFlight_Desc", "Allow flying. Enable for flight mods" },
        { "ServerProperties_RCON", "RCON" },
        { "ServerProperties_EnableRcon", "Enable RCON" },
        { "ServerProperties_EnableRcon_Desc", "Remote server management over network" },
        { "ServerProperties_RconPassword", "RCON Password" },
        { "ServerProperties_RconPassword_Desc", "Password for RCON connection" },
        { "ServerProperties_RconPort", "RCON Port" },
        { "ServerProperties_RconPort_Desc", "Port for RCON connections" },
        { "ServerProperties_RconIp", "RCON IP" },
        { "ServerProperties_RconIp_Desc", "IP for RCON. Default = all interfaces" },
        { "ServerProperties_Permissions", "Permissions" },
        { "ServerProperties_SpawnProtection", "Spawn Protection" },
        { "ServerProperties_SpawnProtection_Desc", "Protection radius around spawn. 0 = disabled" },
        { "ServerProperties_SpawnRadius", "Spawn Radius" },
        { "ServerProperties_SpawnRadius_Desc", "Where players spawn relative to the spawn point" },
        { "ServerProperties_OpPermissionLevel", "OP Permission Level" },
        { "ServerProperties_OpPermissionLevel_Desc", "Maximum access level (1–4). 4 = all commands" },
        { "ServerProperties_MaxTickTime", "Max Tick Time" },
        { "ServerProperties_MaxTickTime_Desc", "Max tick time in ms (-1 = disabled)" },
        { "ServerProperties_NetworkCompression", "Network Compression" },
        { "ServerProperties_NetworkCompression_Desc", "Packet compression threshold" },
        { "ServerProperties_SpawnNPCs", "Spawn NPCs" },
        { "ServerProperties_SpawnNPCs_Desc", "Villager spawning" },
        { "ServerProperties_SpawnAnimals", "Spawn Animals" },
        { "ServerProperties_SpawnAnimals_Desc", "Cow, pig, and other animal spawning" },
        { "ServerProperties_SpawnMonsters", "Spawn Monsters" },
        { "ServerProperties_SpawnMonsters_Desc", "Zombie, skeleton, and creeper spawning" },
        { "ServerProperties_EnabledPacks", "Enabled Datapacks" },
        { "ServerProperties_EnabledPacks_Desc", "List of enabled datapacks, comma-separated" },
        { "ServerProperties_DisabledPacks", "Disabled Datapacks" },
        { "ServerProperties_DisabledPacks_Desc", "List of disabled datapacks, comma-separated" },
        { "ServerProperties_Reset", "Reset" },
        { "ServerProperties_Refresh", "Refresh" },
        { "ServerProperties_Performance", "Performance" },
        { "ServerProperties_Gameplay", "Gameplay" },
        { "ServerProperties_EnableStatus", "Enable Status" },
        { "ServerProperties_EnableStatus_Desc", "Show server status in server list" },
        { "ServerProperties_ForceGamemode", "Force Gamemode" },
        { "ServerProperties_ForceGamemode_Desc", "Force players to use server gamemode" },
        { "ServerProperties_GeneratorSettings", "Generator Settings" },
        { "ServerProperties_GeneratorSettings_Desc", "World generation parameters (JSON)" },
        { "ServerProperties_PreventProxyConnections", "Block Proxies" },
        { "ServerProperties_PreventProxyConnections_Desc", "Prevent connections through proxy servers" },
        { "ServerProperties_RateLimit", "Rate Limit" },
        { "ServerProperties_RateLimit_Desc", "Max packets per second (0 = unlimited)" },
        { "ServerProperties_PlayerIdleTimeout", "Idle Timeout" },
        { "ServerProperties_PlayerIdleTimeout_Desc", "Kick after X minutes of inactivity (0 = off)" },
        { "ServerProperties_AcceptsTransfers", "Accept Transfers" },
        { "ServerProperties_AcceptsTransfers_Desc", "Accept world transfers from other servers" },
        { "ServerProperties_StatusHeartbeatInterval", "Heartbeat Interval" },
        { "ServerProperties_StatusHeartbeatInterval_Desc", "Status report interval (0 = default)" },
        { "ServerProperties_HideOnlinePlayers", "Hide Players" },
        { "ServerProperties_HideOnlinePlayers_Desc", "Hide player list from server status" },
        { "ServerProperties_WhitelistSection", "Whitelist" },
        { "ServerProperties_Query", "Query" },
        { "ServerProperties_EnableQuery", "Enable Query" },
        { "ServerProperties_EnableQuery_Desc", "Server info query protocol (GameSpy 4)" },
        { "ServerProperties_QueryPort", "Query Port" },
        { "ServerProperties_QueryPort_Desc", "Port for Query requests" },
        { "ServerProperties_FunctionPermissionLevel", "Function Permission Level" },
        { "ServerProperties_FunctionPermissionLevel_Desc", "Max level for function execution (1-4)" },
        { "ServerProperties_ManagementServer", "Management Server" },
        { "ServerProperties_ManagementServerEnabled", "Enable Management Server" },
        { "ServerProperties_ManagementServerEnabled_Desc", "Enable management server API" },
        { "ServerProperties_ManagementServerHost", "Management Host" },
        { "ServerProperties_ManagementServerHost_Desc", "Management API bind address" },
        { "ServerProperties_ManagementServerPort", "Management Port" },
        { "ServerProperties_ManagementServerPort_Desc", "Management API port" },
        { "ServerProperties_ManagementServerSecret", "Management Secret" },
        { "ServerProperties_ManagementServerSecret_Desc", "API secret key" },
        { "ServerProperties_ManagementServerTlsEnabled", "Management TLS" },
        { "ServerProperties_ManagementServerTlsEnabled_Desc", "Enable TLS for API" },
        { "ServerProperties_ManagementServerTlsKeystore", "TLS Keystore" },
        { "ServerProperties_ManagementServerTlsKeystore_Desc", "Path to keystore file" },
        { "ServerProperties_ManagementServerAllowedOrigins", "Allowed Origins" },
        { "ServerProperties_ManagementServerAllowedOrigins_Desc", "Allowed CORS origins" },
        { "ServerProperties_ResourcePack", "Resource Pack" },
        { "ServerProperties_ResourcePackUrl", "Resource Pack URL" },
        { "ServerProperties_ResourcePackUrl_Desc", "Download link for resource pack" },
        { "ServerProperties_ResourcePackSha1", "Resource Pack SHA1" },
        { "ServerProperties_ResourcePackSha1_Desc", "Resource pack SHA1 hash" },
        { "ServerProperties_ResourcePackId", "Resource Pack ID" },
        { "ServerProperties_ResourcePackId_Desc", "Resource pack identifier" },
        { "ServerProperties_ResourcePackPrompt", "Resource Pack Prompt" },
        { "ServerProperties_ResourcePackPrompt_Desc", "Prompt text when requesting resource pack" },
        { "ServerProperties_RequireResourcePack", "Require Resource Pack" },
        { "ServerProperties_RequireResourcePack_Desc", "Mandatory resource pack download" },
        { "ServerProperties_MaxChainedNeighborUpdates", "Chained Neighbor Updates" },
        { "ServerProperties_MaxChainedNeighborUpdates_Desc", "Max chained neighbor updates (-1 = unlimited)" },
        { "ServerProperties_EntityBroadcastRangePercentage", "Entity Range" },
        { "ServerProperties_EntityBroadcastRangePercentage_Desc", "% range for entity broadcast" },
        { "ServerProperties_SyncChunkWrites", "Sync Chunk Writes" },
        { "ServerProperties_SyncChunkWrites_Desc", "Synchronize chunk writing" },
        { "ServerProperties_UseNativeTransport", "Native Transport" },
        { "ServerProperties_UseNativeTransport_Desc", "Use native Linux support" },
        { "ServerProperties_Logging", "Logging" },
        { "ServerProperties_LogIps", "Log IPs" },
        { "ServerProperties_LogIps_Desc", "Record IP addresses in log" },
        { "ServerProperties_BroadcastConsoleToOps", "Console → OPS" },
        { "ServerProperties_BroadcastConsoleToOps_Desc", "Send console messages to operators" },
        { "ServerProperties_BroadcastRconToOps", "RCON → OPS" },
        { "ServerProperties_BroadcastRconToOps_Desc", "Send RCON messages to operators" },
        { "ServerProperties_EnableJmxMonitoring", "JMX Monitoring" },
        { "ServerProperties_EnableJmxMonitoring_Desc", "Enable JMX monitoring" },
        { "ServerProperties_EnableCodeOfConduct", "Code of Conduct" },
        { "ServerProperties_EnableCodeOfConduct_Desc", "Enable code of conduct enforcement" },
        { "ServerProperties_BugReportLink", "Bug Report Link" },
        { "ServerProperties_BugReportLink_Desc", "URL for submitting bug reports" },
        { "ServerProperties_PauseWhenEmptySeconds", "Pause When Empty" },
        { "ServerProperties_PauseWhenEmptySeconds_Desc", "Seconds to pause when server is empty" },
        { "ServerProperties_RegionFileCompression", "Region File Compression" },
        { "ServerProperties_RegionFileCompression_Desc", "Compression algorithm for world files" },
        { "ServerProperties_RegionFileCompression_Deflate", "Deflate (Zlib)" },
        { "ServerProperties_RegionFileCompression_Lz4", "LZ4" },
        { "ServerProperties_TextFilteringConfig", "Text Filtering Config" },
        { "ServerProperties_TextFilteringConfig_Desc", "Path to text filter configuration file" },
        { "ServerProperties_TextFilteringVersion", "Text Filtering Version" },
        { "ServerProperties_TextFilteringVersion_Desc", "Filter version for config updates" },
        { "ServerProperties_ManagementServerTlsKeystorePassword", "TLS Keystore Password" },
        { "ServerProperties_ManagementServerTlsKeystorePassword_Desc", "Password for TLS keystore" },
        { "ServerProperties_Deprecated", "Legacy Settings" },
        { "ServerDetail_Settings_General", "Server name" },
        { "ServerDetail_Settings_General_Desc", "Server name in app" },
        { "ServerDetail_Settings_Port", "Port" },
        { "ServerDetail_Settings_Port_Desc", "Server port" },
        { "ServerDetail_Settings_RAM", "Memory Allocation" },
        { "ServerDetail_Settings_RAM_Min", "Min RAM (MB)" },
        { "ServerDetail_Settings_RAM_Min_Desc", "Minimum memory size for server" },
        { "ServerDetail_Settings_RAM_Max", "Max RAM (MB)" },
        { "ServerDetail_Settings_RAM_Max_Desc", "Maximum memory size for server" },
        { "ServerDetail_Settings_AutoRestart", "Auto-Restart" },
        { "ServerDetail_Settings_AutoRestart_Enable", "Enable auto-restart" },
        { "ServerDetail_Settings_AutoRestart_Desc", "Automatically restart server on stop" },
        { "ServerDetail_Settings_AutoRestart_Delay", "Restart delay (sec)" },
        { "ServerDetail_Settings_AutoRestart_Delay_Desc", "Delay before automatic restart" },
        { "ServerDetail_Settings_Java_Auto", "Auto-select Java version" },
        { "ServerDetail_Settings_Java_Auto_Desc", "Automatically select Java based on Minecraft version" },
        { "ServerDetail_Settings_Java_Version", "Java Version" },
        { "ServerDetail_Settings_JvmArgs", "JVM Arguments" },
        { "ServerDetail_Settings_JvmArgs_Desc", "One argument per line. Safe to modify or remove." },
        { "Log_ServerStarted", "Server fully loaded" },
        { "Log_JavaVersionMismatch", "JAVA VERSION MISMATCH!" },
        { "Log_JavaVersionMismatch_Detail", "Minecraft {0} requires Java {1} or higher" },
        { "Log_JavaFound", "Found Java: {0} (version {1})" },
        { "Log_JavaPath", "Java path: {0}" },
        { "Log_Solution", "Solution:" },
        { "Log_Solution_Install_Java", "1. Install Java {0}: https://adoptium.net/" },
        { "Log_Solution_Add_Java", "2. Specify Java {0} path in application settings" },
        { "Log_Solution_Older_Minecraft", "3. Or select an older Minecraft version" },
        { "Log_JavaNotFound", "JAVA NOT FOUND!" },
        { "Log_JavaNotFound_Path", "Java path: {0}" },
        { "Log_JavaNotFound_Error", "Error: {0}" },
        { "Log_Solution_Install_Java_General", "1. Install Java: https://adoptium.net/" },
        { "Log_Solution_Add_Java_Settings", "2. Add Java in application settings ('Add Java' button)" },
        { "Log_Solution_Check_PATH", "3. Make sure Java is added to PATH" },
        { "Log_CriticalError", "Critical startup error!" },
        { "Log_ErrorType", "Type: {0}" },
        { "Log_ErrorMessage", "Message: {0}" },
        { "Log_ErrorOutput", "Error output: {0}" },
        { "Log_ServerStoppedWithCode", "Server exited with error code: {0}" },
        { "Log_ServerConfigProblem", "This may indicate a configuration problem" },
        { "Log_MemoryProblem", "or insufficient memory." },
        { "Log_TimeoutForceKill", "Stop timeout, force killing..." },
        { "Log_ForceKillAttempt", "Attempting force kill..." },
        { "Log_ServerNotRunning", "Attempting to send command to stopped server: {0}" },
        { "Log_JavaFromSettingsNotFound", "Java from server settings not found: {0}" },
        { "Log_JavaVersionNotFound_TryDefault", "Java {0}+ not found, trying default Java" },
        { "Log_JavaDefaultNotFound", "Default Java not found: {0}" },
        { "Log_UsingJavaFromPATH", "Using Java from PATH" },
        { "Log_ServerId", "Server ID: {0}" },
        { "Log_ModLoader", "ModLoader: {0} {1}" },
        { "Log_MinecraftVersion", "Minecraft Version: {0}" },
        { "Log_ServerFolder", "Server Folder: {0}" },
        { "Log_LaunchType", "Launch Type: {0}" },
        { "Log_JarFile", "JAR File: {0} ({1} MB)" },
        { "Log_JavaVersion", "Java Version: {0}" },
        { "Log_JavaPath_Info", "Java Path: {0}" },
        { "Log_JavaArgs", "Java Arguments: {0}" },
        { "Log_WorkingDirectory", "Working Directory: {0}" },
        { "Log_LaunchingProcess", "Launching process..." },
        { "Log_WaitingForStartup", "Waiting for server startup..." },
        { "Log_LaunchCancelled", "Launch cancelled" },
        { "Log_EulaAccepted", "EULA accepted" },
        { "Log_JavaVersionCompatible", "Java version is compatible (requires {0}+)" },
        { "Log_ProcessStarted", "Process started, PID: {0}" },
        { "Log_LaunchForceCancelled", "Launch force cancelled" },
        { "Log_ProcessForceKilled", "Process force killed (server not yet loaded)" },
        { "Log_ExitError", "Exit error: {0}" },
        { "Log_StoppingServer", "Stopping server..." },
        { "Log_SendingStopCommand", "Sending 'stop' command..." },
        { "Log_WaitingForProcessExit", "Waiting for process to exit (60 sec)..." },
        { "Log_ProcessForceKilledAfterTimeout", "Process force killed after timeout" },
        { "Log_ServerStoppedSuccessfully", "Server stopped successfully" },
        { "Log_StopCancelled", "Stop cancelled" },
        { "Log_KillFailedOnCancel", "Failed to kill process on cancel: {0}" },
        { "Log_StopError", "Stop error: {0}" },
        { "Log_CommandSent", "> {0}" },
        { "Log_CommandSendError", "Failed to send command '{0}': {1}" },
        { "Log_OldLogDeleted", "Old log deleted: latest.log" },
        { "Log_LogMoved", "Locked log moved: latest.log -> {0}" },
        { "Log_CleanupFailed", "Failed to clean old logs: {0}" },
        { "Log_ConfigUnavailable", "Config unavailable, using Java from PATH" },
        { "Log_UsingServerJava", "Using Java from server settings: {0}" },
        { "Log_AutoSelectJava", "Auto-selecting Java: requires Java {0}+ for Minecraft {1}" },
        { "Log_JavaSelected", "Selected Java: {0}" },
        { "Log_UsingJava", "Using Java: {0}" },
        { "Log_AutoRestart", "Auto-restart in" },
        { "Log_Seconds", "sec" },
        { "Log_ServerFullyLoaded", "Server fully loaded" },
        { "Log_ServerStarting", "Starting server: {0}" },
        { "Log_KillFailed", "Failed to kill process: {0}" },
        { "Log_ServerStoppedCode0", "Server stopped (exit code: 0)" },
        { "Log_MonitorCancelled", "Process monitoring cancelled" },
        { "Log_MonitorError", "Process monitoring error: {0}" },
        { "Message_ConfirmDelete", "Are you sure you want to delete the server?" },
        { "Message_Error", "Error" },
        { "Message_DeleteMod", "Delete" },
        { "Message_DeletePlugin", "Delete" },
        { "Message_RestartRequired", "Application restart is required to apply the new language." },
        { "Error_JavaNotFound", "Java not found" },
        { "Error_JavaIncompatible", "Incompatible Java version" },
        { "Error_ServerInstallFailed", "Server installation failed" },
        { "Error_PortInUse", "Port is already in use" },
        { "Error_OutOfMemory", "Out of memory" },
        { "Snackbar_JavaIncompatible_Title", "Incompatible Java" },
        { "Snackbar_JavaIncompatible_Message", "Minecraft {0} requires Java {1}+, found Java {2}.\nThe server will not start with the current Java version." },
        { "Snackbar_JavaIncompatible_Message_Plural", "Minecraft {0} requires Java {1}+, found Java: {2}.\nThe server will not start with the current Java versions." },
        { "JavaError_Title", "Java Error" },
        { "JavaError_Required", "Java installation or update is required" },
        { "JavaError_DownloadText", "Download the latest Java version from the official website:" },
        { "JavaError_DownloadBtn", "Download Java (adoptium.net)" },
        { "Common_NotSelected", "Not selected" },
        { "Common_Default", "Default" },
        { "Common_Unknown", "Unknown" },
        { "Common_Preparing", "Preparing..." },
        { "Settings_SelectServerFolder", "Select servers folder" },
        { "Settings_SelectJava", "Select java.exe or javaw.exe" },
        { "Settings_JavaFilter", "Java executable|java.exe|JavaW executable|javaw.exe" },
        { "Settings_JavaAdded", "Java added" },
        { "Settings_JavaVersion", "Version" },
        { "Settings_JavaPath", "Path" },
        { "Settings_JavaInvalid", "Failed to add Java. Check the file path.\n\nMake sure the selected file is java.exe or javaw.exe" },
        { "Props_Loaded", "Properties loaded" },
        { "Props_NotLoaded", "Error: file not loaded" },
        { "Props_Saved", "Properties saved!" },
        { "Props_SaveError", "Save error" },
        { "Props_Reset", "Properties reset" },
        { "ServerDetail_OperationError", "Failed to perform operation" },
        { "ServerDetail_OpenFolderError", "Failed to open server folder" },
        { "ServerDetail_PropsLoadError", "Error loading properties" },
        { "ServerDetail_ModsLoadError", "Error loading mods" },
        { "ServerDetail_PluginsLoadError", "Error loading plugins" },
        { "ServerDetail_ModsFolderNotFound", "Mods folder not found" },
        { "ServerDetail_PluginsFolderNotFound", "Plugins folder not found" },
        { "ServerDetail_FolderOpenError", "Failed to open folder" },
        { "ServerDetail_DeleteModConfirm", "Delete mod \"{0}\"?\n\nFile: {1}" },
        { "ServerDetail_DeleteModTitle", "Delete Mod" },
        { "ServerDetail_DeletePluginConfirm", "Delete plugin \"{0}\"?\n\nFile: {1}" },
        { "ServerDetail_DeletePluginTitle", "Delete Plugin" },
        { "ServerDetail_ModDeleteError", "Error deleting mod" },
        { "ServerDetail_PluginDeleteError", "Error deleting plugin" },
        { "ServerDetail_DeleteServerError", "Error deleting server" },
        { "ServerDetail_JavaDefault", "Default" },
        { "ServerDetail_JavaNotSelected", "not selected" },
        { "ServersPage_AppNotInitialized", "Error: application not initialized" },
        { "ServersPage_OpenFolderWarning", "Failed to open server folder" },
        { "ServersPage_DeleteError", "Error deleting server" },
        { "ServersPage_OperationError", "Failed to perform operation" },
        { "App_StartupError", "Application initialization error" },
        { "App_StartupErrorDetail", "Check logs in %AppData%\\Konserva\\Logs" },
        { "App_UnhandledError", "Unhandled exception" },
        { "App_UnhandledErrorDetail", "Application will be closed." },

        { "Settings_Download", "Downloads" },
        { "Settings_DownloadSource", "Download Source" },
        { "Settings_DownloadSource_Desc", "Where to download modloader and game files" },
        { "Settings_DownloadSource_VanillaApi", "Official Minecraft API" },
        { "Settings_DownloadSource_BMCLAPI", "BMCLAPI (mirror, faster in China/Russia)" }
    };
}