using System.Collections.Generic;

namespace Konserva.Localization;

public static class RussianStrings
{
    public static readonly Dictionary<string, string> Translations = new Dictionary<string, string>
    {
        { "MainWindow_Settings", "Настройки" },
        { "MainWindow_Header", "Konserva Manager" },
        { "StatusBar_TotalServers", "Всего серверов" },
        { "StatusBar_Running", "Запущено" },
        { "StatusBar_Memory", "Память" },
        { "Update_Button", "Обновить" },
        { "Update_Downloading", "Загрузка..." },
        { "Update_Installing", "Установка..." },
        { "Update_Success", "Перезапуск..." },
        { "Update_Retry", "Повторить" },
        { "Update_Available_Tooltip", "Нажмите для обновления" },
        { "Update_Failed_Tooltip", "Ошибка обновления. Нажмите для повтора." },
        { "Settings_CheckForUpdates", "Проверить обновления" },
        { "Settings_UpToDate_Button", "Актуальная версия" },
        { "Settings_UpdateAvailable_Button", "Доступно обновление {0}" },
        { "Settings_UpdateCheckError", "Ошибка проверки обновлений" },
        { "Settings_Title", "Настройки" },
        { "Settings_Base", "Глобальные" },
        { "Settings_Servers_Dir", "Папка серверов" },
        { "Settings_Servers_DirDesc", "Каталог для файлов серверов" },
        { "Settings_Servers_Browse", "Обзор" },
        { "Settings_Java", "Java" },
        { "Settings_Java_Empty", "Ни одной Java не установлено!" },
        { "Settings_Java_Add", "Добавить Java" },
        { "Settings_Java_Delete", "Удалить" },
        { "Settings_Java_Delete_Confirm_Title", "Удалить Java?" },
        { "Settings_Java_Delete_Confirm_Message", "Вы уверены, что хотите удалить эту установку Java?" },
        { "Settings_Java_Delete_Failed", "Не удалось удалить Java" },
        { "Settings_Java_Scan", "Сканировать" },
        { "Settings_Java_Scanning", "Сканирование..." },
        { "Settings_Java_Scan_Success", "Найдено Java: {0}" },
        { "Settings_Java_Scan_NoneFound", "Установленные Java не найдены" },
        { "Settings_Java_Scan_Error", "Ошибка при сканировании Java" },
        { "Settings_CheckUpdates", "Проверка обновлений" },
        { "Settings_CheckUpdates_Desc", "Автоматически проверять обновления" },
        { "Settings_CheckUpdates_OnLaunch", "При запуске" },
        { "Settings_CheckUpdates_Scheduled", "По расписанию" },
        { "Settings_CheckUpdates_Interval", "Интервал проверки" },
        { "Settings_CheckUpdates_Interval_Desc", "Как часто проверять обновления" },
        { "Settings_MinimizeToTray", "Сворачивать в трей" },
        { "Settings_MinimizeToTray_Desc", "Управление сворачиванием в системный трей при закрытии или сворачивании окна" },
        { "Settings_MinimizeToTray_None", "Выключено" },
        { "Settings_MinimizeToTray_OnClose", "При закрытии" },
        { "Settings_MinimizeToTray_OnMinimize", "При сворачивании" },
        { "Settings_MinimizeToTray_Always", "Всегда" },
        { "Settings_Appearance", "Внешний вид" },
        { "Settings_Theme", "Тема" },
        { "Settings_Theme_Desc", "Выберите тему приложения" },
        { "Settings_Theme_System", "Как в системе" },
        { "Settings_Theme_Dark", "Тёмная" },
        { "Settings_Theme_Light", "Светлая" },
        { "Settings_Language", "Язык" },
        { "Settings_Language_Desc", "Выберите язык приложения" },
        { "Settings_Language_System", "Как в системе" },
        { "Settings_Language_English", "Английский" },
        { "Settings_Language_Russian", "Русский" },
        { "Settings_About", "О программе" },
        { "Settings_About_Description", "Менеджер серверов Minecraft" },
        { "Settings_About_ModalLoaders", "Поддерживаемые модлоадеры:" },
        { "Message_SettingsSaved", "Настройки сохранены" },
        { "Validation_NameRequired", "Введите название сервера" },
        { "Validation_RamMinRequired", "Введите мин. ОЗУ" },
        { "Validation_RamMaxRequired", "Введите макс. ОЗУ" },
        { "Validation_AutoRestartDelayRequired", "Введите задержку перезапуска" },
        { "Validation_JvmArgsRequired", "Введите JVM аргументы" },
        { "CreateServer_Title", "Создать сервер" },
        { "CreateServer_Name", "Название сервера" },
        { "CreateServer_MinecraftVersion", "Версия Minecraft" },
        { "CreateServer_ModLoader", "Модлоадер" },
        { "CreateServer_ModLoaderVersion", "Версия модлоадера" },
        { "CreateServer_Folder", "Папка" },
        { "CreateServer_Create", "Создать" },
        { "CreateServer_Browse", "Обзор" },
        { "CreateServer_Cancel", "Отмена" },
        { "CreateServer_Filter_Stable", "Показывать тестовые версии" },
        { "CreateServer_Not_Found", "Не найдено" },
        { "CreateServer_Import", "Импортировать" },
        { "CreateServer_Error_DialogLoad", "Ошибка загрузки диалога" },
        { "CreateServer_Import_Duplicate", "Сервер из этой папки уже импортирован:\n{0}" },
        { "CreateServer_Import_NoJar", "В выбранной папке не найден JAR файл сервера." },
        { "CreateServer_Import_Success", "Сервер \"{0}\" успешно импортирован!" },
        { "CreateServer_Import_Success_Title", "Импорт завершён" },
        { "CreateServer_Import_Error", "Ошибка импорта сервера" },
        { "CreateServer_Error_NoServerManager", "ServerManager не инициализирован!" },
        { "CreateServer_Validation_NoName", "Введите название сервера" },
        { "CreateServer_Validation_NoLoaderVersion", "Выберите версию модлоадера" },
        { "CreateServer_Validation_NoFolder", "Выберите папку сервера" },
        { "CreateServer_Error_DuplicateName", "Сервер с именем \"{0}\" уже существует. Пожалуйста, выберите другое имя." },
        { "CreateServer_Error_CreateFailed", "Ошибка при создании сервера" },
        { "CreateServer_Error_InstallFailed", "Не удалось установить сервер" },
        { "CreateServer_Error_InstallFailed_Exception", "Ошибка при установке сервера" },
        { "CreateServer_Browse_Title", "Выберите папку для сервера" },
        { "CreateServer_Import_Title", "Выберите папку с сервером" },
        { "CreateServer_Installing_Preparing", "Подготовка..." },
        { "CreateServer_Installing_Progress", "Установка {0}..." },
        { "CreateServer_Install_Error", "Ошибка: {0}" },
        { "CreateServer_Install_Cancelled", "Отменено" },
        { "CreateServer_Install_Ready", "Готов" },
        { "Installer_Downloading", "Загрузка {0}..." },
        { "Installer_DownloadingServer", "Загрузка сервера..." },
        { "Installer_CreatingConfig", "Создание конфигурации..." },
        { "Installer_Finishing", "Завершение..." },
        { "Installer_ChangingSource", "Смена источника..." },
        { "Installer_DownloadingInstaller", "Загрузка установщика..." },
        { "Installer_RunningInstaller", "Установка {0}..." },
        { "Installer_Finalizing", "Завершение..." },
        { "Installer_Extracting", "Распаковка и загрузка..." },
        { "Installer_ApplyingPatches", "Применение патчей ({0}K)..." },
        { "Installer_Preparing", "Подготовка..." },
        { "Installer_Configuring", "Настройка сервера..." },
        { "Installer_Installing", "Установка..." },
        { "Installer_Running", "Запуск установщика..." },
        { "Installer_Success", "Установка завершена!" },
        { "Installer_ShowLog", "Показать лог" },
        { "Installer_Log_Title", "Лог установки" },
        { "CreateServer_Validation_PathEmpty", "Путь к серверу не может быть пустым" },
        { "CreateServer_Validation_InvalidChars", "Путь содержит недопустимые символы" },
        { "CreateServer_Validation_PathTooLong", "Путь слишком длинный (максимум {0} символов)" },
        { "CreateServer_Validation_FileNotFolder", "Указанный путь является файлом, а не папкой" },
        { "CreateServer_Validation_SystemFolder", "Нельзя создавать серверы в системных папках Windows" },
        { "CreateServer_Validation_FolderNotEmpty", "Папка не пуста ({0} файлов). Убедитесь, что это правильное место для сервера." },
        { "CreateServer_Validation_ParentNotFound", "Родительская папка не существует" },
        { "CreateServer_Validation_NoPermission", "Недостаточно прав для создания папки" },
        { "CreateServer_Validation_Error", "Ошибка валидации пути: {0}" },
        { "ServersPage_Search", "Поиск..." },
        { "ServersPage_Filter_All", "Все типы" },
        { "ServersPage_Filter_AllServers", "Все серверы" },
        { "ServersPage_Filter_Running", "Запущен" },
        { "ServersPage_Filter_Stopped", "Остановлен" },
        { "ServersPage_SortBy", "Сортировка" },
        { "ServersPage_Sort_Header", "Сортировать по" },
        { "ServersPage_Sort_Name", "Названию" },
        { "ServersPage_Sort_Status", "Статусу" },
        { "ServersPage_Sort_Type", "Типу" },
        { "ServersPage_Sort_Version", "Версии" },
        { "ServersPage_Filter_Status", "Статус" },
        { "ServersPage_Create", "Создать сервер" },
        { "ServersPage_Port", "Порт:" },
        { "ServersPage_OpenFolder", "Открыть папку сервера" },
        { "ServersPage_Delete", "Удалить сервер" },
        { "ServersPage_NoServers", "Нет серверов" },
        { "ServersPage_NoServers_Description", "Создайте первый сервер для управления" },
        { "Common_Copied", "Скопировано!" },
        { "Common_None", "Нет" },
        { "MsgBtn_OK", "ОК" },
        { "MsgBtn_Yes", "Да" },
        { "MsgBtn_No", "Нет" },
        { "MsgBtn_Cancel", "Отмена" },
        { "MsgBtn_Delete", "Удалить" },
        { "UiHelper_OpenFolderError", "Не удалось открыть папку" },
        { "MsgTitle_Info", "Информация" },
        { "MsgTitle_Warning", "Предупреждение" },
        { "MsgTitle_Error", "Ошибка" },
        { "MsgTitle_Confirm", "Подтверждение" },
        { "MsgDel_Title", "Удаление сервера" },
        { "MsgDel_Confirm", "Вы уверены, что хотите удалить сервер \"{0}\"?" },
        { "MsgDel_Irreversible", "Это действие необратимо!" },
        { "ServerDetail_Console", "Консоль" },
        { "ServerDetail_Properties", "Файл server.properties" },
        { "ServerDetail_Settings", "Настройки сервера" },
        { "ServerDetail_Mods", "Моды" },
        { "ServerDetail_Plugins", "Плагины" },
        { "ServerDetail_Start", "Запустить" },
        { "ServerDetail_Stop", "Остановить" },
        { "ServerDetail_StartStop", "Запустить/Остановить" },
        { "ServerDetail_Starting", "Запускается..." },
        { "ServerDetail_Stopping", "Останавливается..." },
        { "ServerStatus_Error", "Ошибка" },
        { "ServerDetail_Delete", "Удалить" },
        { "ServerDetail_OpenFolder", "Открыть папку" },
        { "ServerDetail_Java", "Java" },
        { "ServerDetail_Console_Empty", "Консоль пуста, запустите сервер" },
        { "ServerDetail_SendCommand", "Отправить" },
        { "ServerDetail_Mods_List", "Список модов" },
        { "ServerDetail_Mods_OpenFolder", "Открыть папку mods" },
        { "ServerDetail_Mods_Refresh", "Обновить" },
        { "ServerDetail_Mods_Delete", "Удалить" },
        { "ServerDetail_Mods_ToggleAll", "Вкл/Выкл все" },
        { "ServerDetail_Mods_ToggleAll_Enable", "Включить все моды" },
        { "ServerDetail_Mods_ToggleAll_Disable", "Отключить все моды" },
        { "ServerDetail_Plugins_List", "Список плагинов" },
        { "ServerDetail_Plugins_OpenFolder", "Открыть папку plugins" },
        { "ServerDetail_Plugins_Refresh", "Обновить" },
        { "ServerDetail_Plugins_Delete", "Удалить" },
        { "ServerDetail_Plugins_ToggleAll", "Вкл/Выкл все" },
        { "ServerDetail_Plugins_ToggleAll_Enable", "Включить все плагины" },
        { "ServerDetail_Plugins_ToggleAll_Disable", "Отключить все плагины" },
        { "ServerProperties_Save", "Сохранить" },
        { "ServerProperties_FileNotCreated", "Файл server.properties ещё не создан" },
        { "ServerProperties_FileNotCreated_Hint", "Файл создастся автоматически при первом запуске сервера" },
        { "ServerProperties_General", "Основные" },
        { "ServerProperties_ServerPort", "Порт сервера" },
        { "ServerProperties_ServerPort_Desc", "Игровой порт (пробросьте на роутере)" },
        { "ServerProperties_ServerIp", "IP сервера" },
        { "ServerProperties_ServerIp_Desc", "Пусто = все интерфейсы" },
        { "ServerProperties_MaxPlayers", "Макс. игроков" },
        { "ServerProperties_MaxPlayers_Desc", "Максимум игроков одновременно" },
        { "ServerProperties_ViewDistance", "Дальность прорисовки" },
        { "ServerProperties_ViewDistance_Desc", "Дальность прорисовки чанков клиентом" },
        { "ServerProperties_SimulationDistance", "Дальность симуляции" },
        { "ServerProperties_SimulationDistance_Desc", "Расстояние обновления сущностей и мира" },
        { "ServerProperties_Gamemode", "Режим игры" },
        { "ServerProperties_Gamemode_Desc", "Режим по умолчанию для новых игроков" },
        { "ServerProperties_Gamemode_Survival", "Выживание" },
        { "ServerProperties_Gamemode_Creative", "Творчество" },
        { "ServerProperties_Gamemode_Adventure", "Приключение" },
        { "ServerProperties_Gamemode_Spectator", "Наблюдатель" },
        { "ServerProperties_Difficulty", "Сложность" },
        { "ServerProperties_Difficulty_Desc", "Урон мобов, голод и механики выживания" },
        { "ServerProperties_Difficulty_Peaceful", "Мирный" },
        { "ServerProperties_Difficulty_Easy", "Лёгкий" },
        { "ServerProperties_Difficulty_Normal", "Обычный" },
        { "ServerProperties_Difficulty_Hard", "Сложный" },
        { "ServerProperties_Hardcore", "Хардкор" },
        { "ServerProperties_Hardcore_Desc", "Смерть навсегда (нельзя отключить на работающем сервере)" },
        { "ServerProperties_PvP", "PvP" },
        { "ServerProperties_PvP_Desc", "Разрешить бой между игроками" },
        { "ServerProperties_CommandBlocks", "Командные блоки" },
        { "ServerProperties_CommandBlocks_Desc", "Включить командные блоки" },
        { "ServerProperties_World", "Мир" },
        { "ServerProperties_LevelName", "Имя мира" },
        { "ServerProperties_LevelName_Desc", "Имя папки с сохранением мира" },
        { "ServerProperties_LevelSeed", "Сид (seed)" },
        { "ServerProperties_LevelSeed_Desc", "Сид мира (пусто = случайный)" },
        { "ServerProperties_LevelType", "Тип мира" },
        { "ServerProperties_LevelType_Desc", "Тип генерации ландшафта" },
        { "ServerProperties_LevelType_Normal", "Обычный" },
        { "ServerProperties_LevelType_Flat", "Плоский" },
        { "ServerProperties_LevelType_LargeBiomes", "Крупные биомы" },
        { "ServerProperties_LevelType_Amplified", "Амплифицированный" },
        { "ServerProperties_LevelType_SingleBiome", "Один биом" },
        { "ServerProperties_MaxWorldSize", "Макс. размер мира" },
        { "ServerProperties_MaxWorldSize_Desc", "Радиус мира в блоках" },
        { "ServerProperties_SpawnStructures", "Генерация структур" },
        { "ServerProperties_SpawnStructures_Desc", "Деревни, храмы, крепости и т.д." },
        { "ServerProperties_AllowNether", "Нижний мир" },
        { "ServerProperties_AllowNether_Desc", "Разрешить доступ в Нижний мир через портал" },
        { "ServerProperties_Network", "Сеть" },
        { "ServerProperties_OnlineMode", "Проверка лицензии" },
        { "ServerProperties_OnlineMode_Desc", "Отключите для пиратских клиентов" },
        { "ServerProperties_Whitelist", "Белый список" },
        { "ServerProperties_Whitelist_Desc", "Только игроки из белого списка могут зайти" },
        { "ServerProperties_EnforceWhitelist", "Принудительный белый список" },
        { "ServerProperties_EnforceWhitelist_Desc", "Кикать игроков, удалённых из белого списка" },
        { "ServerProperties_EnforceSecureProfile", "Безопасный профиль" },
        { "ServerProperties_EnforceSecureProfile_Desc", "Требовать подписанный профиль клиента" },
        { "ServerProperties_AllowFlight", "Разрешить полёт" },
        { "ServerProperties_AllowFlight_Desc", "Разрешить полёт (включите для модов с полётом)" },
        { "ServerProperties_RCON", "RCON" },
        { "ServerProperties_EnableRcon", "Включить RCON" },
        { "ServerProperties_EnableRcon_Desc", "Удалённое управление сервером по сети" },
        { "ServerProperties_RconPassword", "Пароль RCON" },
        { "ServerProperties_RconPassword_Desc", "Пароль для RCON подключения" },
        { "ServerProperties_RconPort", "Порт RCON" },
        { "ServerProperties_RconPort_Desc", "Порт для RCON подключений" },
        { "ServerProperties_Permissions", "Разрешения" },
        { "ServerProperties_SpawnProtection", "Защита спавна" },
        { "ServerProperties_SpawnProtection_Desc", "Радиус защиты спавна (0 = выкл)" },
        { "ServerProperties_SpawnNPCs", "Спавн NPC" },
        { "ServerProperties_SpawnNPCs_Desc", "Появление NPC (жителей)" },
        { "ServerProperties_SpawnAnimals", "Спавн животных" },
        { "ServerProperties_SpawnAnimals_Desc", "Появление животных (коров, свиней и т.д.)" },
        { "ServerProperties_SpawnMonsters", "Спавн монстров" },
        { "ServerProperties_SpawnMonsters_Desc", "Появление монстров (зомби, криперов и т.д.)" },
        { "ServerProperties_SpawnRadius", "Радиус спавна" },
        { "ServerProperties_SpawnRadius_Desc", "Смещение спавна игрока от точки спавна" },
        { "ServerProperties_OpPermissionLevel", "Уровень прав OP" },
        { "ServerProperties_OpPermissionLevel_Desc", "Макс. уровень доступа оператора (1-4)" },
        { "ServerProperties_ForceGamemode", "Принудительный режим" },
        { "ServerProperties_ForceGamemode_Desc", "Принудительно установить режим сервера игрокам" },
        { "ServerProperties_GeneratorSettings", "Настройки генератора" },
        { "ServerProperties_GeneratorSettings_Desc", "Параметры генерации мира (JSON)" },
        { "ServerProperties_PreventProxyConnections", "Блокировка прокси" },
        { "ServerProperties_PreventProxyConnections_Desc", "Блокировать подключения через прокси" },
        { "ServerProperties_RateLimit", "Лимит запросов" },
        { "ServerProperties_RateLimit_Desc", "Макс. пакетов/сек (0 = без лимита)" },
        { "ServerProperties_PlayerIdleTimeout", "Таймаут бездействия" },
        { "ServerProperties_PlayerIdleTimeout_Desc", "Кикать через X мин бездействия (0 = выкл)" },
        { "ServerProperties_AcceptsTransfers", "Принимать трансферы" },
        { "ServerProperties_AcceptsTransfers_Desc", "Принимать переносы миров с других серверов" },
        { "ServerProperties_StatusHeartbeatInterval", "Интервал heartbeat" },
        { "ServerProperties_StatusHeartbeatInterval_Desc", "Интервал отчёта статуса (0 = по умолч.)" },
        { "ServerProperties_HideOnlinePlayers", "Скрыть игроков" },
        { "ServerProperties_HideOnlinePlayers_Desc", "Скрыть игроков из статуса сервера" },
        { "ServerProperties_WhitelistSection", "Белый список" },
        { "ServerProperties_Query", "Query" },
        { "ServerProperties_EnableQuery", "Включить Query" },
        { "ServerProperties_EnableQuery_Desc", "Протокол GameSpy 4 Query" },
        { "ServerProperties_QueryPort", "Порт Query" },
        { "ServerProperties_QueryPort_Desc", "Порт для Query запросов" },
        { "ServerProperties_FunctionPermissionLevel", "Уровень прав функций" },
        { "ServerProperties_FunctionPermissionLevel_Desc", "Макс. уровень для функций (1-4)" },
        { "ServerProperties_MaxTickTime", "Макс. время тика" },
        { "ServerProperties_MaxTickTime_Desc", "Макс. время тика в мс (-1 = отключено)" },
        { "ServerProperties_NetworkCompression", "Сжатие сети" },
        { "ServerProperties_NetworkCompression_Desc", "Порог сжатия пакетов" },
        { "ServerProperties_EnabledPacks", "Включённые датапаки" },
        { "ServerProperties_EnabledPacks_Desc", "Включённые датапаки (через запятую)" },
        { "ServerProperties_DisabledPacks", "Отключённые датапаки" },
        { "ServerProperties_DisabledPacks_Desc", "Отключённые датапаки (через запятую)" },
        { "ServerProperties_Reset", "Сбросить" },
        { "ServerProperties_Refresh", "Обновить" },
        { "ServerProperties_Performance", "Производительность" },
        { "ServerProperties_MaxChainedNeighborUpdates", "Цепные обновления" },
        { "ServerProperties_MaxChainedNeighborUpdates_Desc", "Макс. цепных обновлений соседей (-1 = без лимита)" },
        { "ServerProperties_EntityBroadcastRangePercentage", "Дальность сущностей" },
        { "ServerProperties_EntityBroadcastRangePercentage_Desc", "% дальности рассылки сущностей" },
        { "ServerProperties_SyncChunkWrites", "Синхр. запись чанков" },
        { "ServerProperties_SyncChunkWrites_Desc", "Синхронизировать запись чанков" },
        { "ServerProperties_UseNativeTransport", "Нативный транспорт" },
        { "ServerProperties_UseNativeTransport_Desc", "Нативный транспорт Linux" },
        { "ServerProperties_Logging", "Логирование" },
        { "ServerProperties_LogIps", "Логировать IP" },
        { "ServerProperties_LogIps_Desc", "Записывать IP-адреса" },
        { "ServerProperties_BroadcastConsoleToOps", "Консоль → OPS" },
        { "ServerProperties_BroadcastConsoleToOps_Desc", "Пересылать консоль операторам" },
        { "ServerProperties_BroadcastRconToOps", "RCON → OPS" },
        { "ServerProperties_BroadcastRconToOps_Desc", "Пересылать RCON операторам" },
        { "ServerProperties_EnableJmxMonitoring", "JMX мониторинг" },
        { "ServerProperties_EnableJmxMonitoring_Desc", "Включить JMX мониторинг" },
        { "ServerProperties_EnableCodeOfConduct", "Кодекс поведения" },
        { "ServerProperties_EnableCodeOfConduct_Desc", "Применять кодекс поведения" },
        { "ServerProperties_BugReportLink", "Ссылка на баг-репорт" },
        { "ServerProperties_BugReportLink_Desc", "URL для баг-репортов" },
        { "ServerProperties_PauseWhenEmptySeconds", "Пауза при пустом сервере" },
        { "ServerProperties_PauseWhenEmptySeconds_Desc", "Пауза тиков, когда нет игроков" },
        { "ServerProperties_RegionFileCompression", "Сжатие файлов регионов" },
        { "ServerProperties_RegionFileCompression_Desc", "Алгоритм сжатия файлов мира" },
        { "ServerProperties_RegionFileCompression_Deflate", "Deflate (Zlib)" },
        { "ServerProperties_RegionFileCompression_Lz4", "LZ4" },
        { "ServerProperties_TextFilteringConfig", "Конфиг фильтрации текста" },
        { "ServerProperties_TextFilteringConfig_Desc", "Путь к конфигу фильтрации текста" },
        { "ServerProperties_TextFilteringVersion", "Версия фильтрации текста" },
        { "ServerProperties_TextFilteringVersion_Desc", "Версия для обновлений конфига" },
        { "ServerProperties_ManagementServerTlsKeystorePassword", "Пароль keystore TLS" },
        { "ServerProperties_ManagementServerTlsKeystorePassword_Desc", "Пароль для TLS keystore" },
        { "ServerDetail_Settings_General", "Название сервера" },
        { "ServerDetail_Settings_General_Desc", "Название сервера в приложении" },
        { "ServerDetail_Settings_RAM", "Выделение памяти" },
        { "ServerDetail_Settings_RAM_Min", "Мин. ОЗУ (МБ)" },
        { "ServerDetail_Settings_RAM_Min_Desc", "Минимум памяти для сервера" },
        { "ServerDetail_Settings_RAM_Max", "Макс. ОЗУ (МБ)" },
        { "ServerDetail_Settings_RAM_Max_Desc", "Максимум памяти для сервера" },
        { "ServerDetail_Settings_AutoRestart", "Автоперезапуск" },
        { "ServerDetail_Settings_AutoRestart_Enable", "Включить автоперезапуск" },
        { "ServerDetail_Settings_AutoRestart_Desc", "Авто-перезапуск сервера при остановке" },
        { "ServerDetail_Settings_AutoRestart_Delay", "Задержка перезапуска (сек)" },
        { "ServerDetail_Settings_AutoRestart_Delay_Desc", "Задержка перед автоперезапуском" },
        { "ServerDetail_Settings_Java_Auto", "Автовыбор Java" },
        { "ServerDetail_Settings_Java_Auto_Desc", "Авто-выбор Java по версии Minecraft" },
        { "ServerDetail_Settings_Java_Version", "Версия Java" },
        { "ServerDetail_Settings_JvmArgs", "JVM аргументы" },
        { "ServerDetail_Settings_JvmArgs_Desc", "По одному аргументу на строку" },
        { "Log_ServerStarted", "Сервер полностью загрузился" },
        { "Log_JavaVersionMismatch", "НЕСОВМЕСТИМОСТЬ ВЕРСИИ JAVA!" },
        { "Log_JavaVersionMismatch_Detail", "Minecraft {0} требует Java {1} или выше" },
        { "Log_JavaFound", "Найдена Java: {0} (версия {1})" },
        { "Log_JavaPath", "Путь к Java: {0}" },
        { "Log_Solution", "Решение:" },
        { "Log_Solution_Install_Java", "1. Установите Java {0}: https://adoptium.net/" },
        { "Log_Solution_Add_Java", "2. Укажите путь к Java {0} в настройках приложения" },
        { "Log_Solution_Older_Minecraft", "3. Или выберите более старую версию Minecraft" },
        { "Log_JavaNotFound", "JAVA НЕ НАЙДЕНА!" },
        { "Log_JavaNotFound_Path", "Путь к Java: {0}" },
        { "Log_JavaNotFound_Error", "Ошибка: {0}" },
        { "Log_Solution_Install_Java_General", "1. Установите Java: https://adoptium.net/" },
        { "Log_Solution_Add_Java_Settings", "2. Добавьте Java в настройках приложения (кнопка 'Добавить Java')" },
        { "Log_Solution_Check_PATH", "3. Убедитесь, что Java добавлена в PATH" },
        { "Log_CriticalError", "Критическая ошибка запуска!" },
        { "Log_ErrorType", "Тип: {0}" },
        { "Log_ErrorMessage", "Сообщение: {0}" },
        { "Log_ErrorOutput", "Вывод ошибки: {0}" },
        { "Log_ServerStoppedWithCode", "Сервер завершился с кодом ошибки: {0}" },
        { "Log_ServerConfigProblem", "Это может означать проблему с конфигурацией" },
        { "Log_MemoryProblem", "или нехватку памяти." },
        { "Log_TimeoutForceKill", "Таймаут остановки, принудительное завершение..." },
        { "Log_ForceKillAttempt", "Попытка принудительного завершения..." },
        { "Log_ServerNotRunning", "Попытка отправки команды на остановленный сервер: {0}" },
        { "Log_JavaFromSettingsNotFound", "Java из настроек сервера не найдена: {0}" },
        { "Log_JavaVersionNotFound_TryDefault", "Не найдена Java {0}+, пробуем Java по умолчанию" },
        { "Log_JavaDefaultNotFound", "Java по умолчанию не найдена: {0}" },
        { "Log_JarFile", "JAR файл: {0} ({1} MB)" },
        { "Log_JavaArgs", "Аргументы Java: {0}" },
        { "Log_LaunchingProcess", "Запуск процесса..." },
        { "Log_WaitingForStartup", "Ожидание запуска сервера..." },
        { "Log_LaunchCancelled", "Запуск отменён" },
        { "Log_EulaAccepted", "EULA принята" },
        { "Log_ProcessStarted", "Процесс запущен, PID: {0}" },
        { "Log_LaunchForceCancelled", "Запуск отменён принудительно" },
        { "Log_ProcessForceKilled", "Процесс завершён принудительно (сервер ещё не загрузился)" },
        { "Log_ExitError", "Ошибка завершения: {0}" },
        { "Log_ProcessForceKilledAfterTimeout", "Процесс завершён принудительно после таймаута" },
        { "Log_ServerStoppedSuccessfully", "Сервер успешно остановлен" },
        { "Log_StopCancelled", "Остановка отменена" },
        { "Log_KillFailedOnCancel", "Не удалось завершить процесс при отмене: {0}" },
        { "Log_StopError", "Ошибка остановки: {0}" },
        { "Log_CommandSent", "> {0}" },
        { "Log_CommandSendError", "Ошибка отправки команды '{0}': {1}" },
        { "Log_ConfigUnavailable", "Конфигурация недоступна, используем Java из PATH" },
        { "Log_AutoRestart", "Авто-рестарт через" },
        { "Log_Seconds", "сек" },
        { "Log_ServerStarting", "Запуск сервера: {0}" },
        { "Log_KillFailed", "Не удалось завершить процесс: {0}" },
        { "Log_MonitorCancelled", "Мониторинг процесса отменён" },
        { "Log_MonitorError", "Ошибка мониторинга процесса: {0}" },
        { "Snackbar_JavaIncompatible_Title", "Несовместимая Java" },
        { "Snackbar_JavaIncompatible_Message", "Для Minecraft {0} требуется Java {1}+, найдена Java {2}.\nСервер не запустится с текущей версией Java." },
        { "Snackbar_JavaIncompatible_Message_Plural", "Для Minecraft {0} требуется Java {1}+, найдены Java: {2}.\nСервер не запустится с текущими версиями Java." },
        { "Common_NotSelected", "Не выбрано" },
        { "Common_Unknown", "Неизвестно" },
        { "Common_Preparing", "Подготовка..." },
        { "Common_Close", "Закрыть" },
        { "Common_Copy", "Копировать" },
        { "Settings_SelectServerFolder", "Выберите папку для серверов" },
        { "Settings_SelectJava", "Выберите java.exe или javaw.exe" },
        { "Settings_JavaFilter", "Java executable|java.exe|JavaW executable|javaw.exe" },
        { "Settings_JavaAdded", "Java добавлена" },
        { "Settings_JavaVersion", "Версия" },
        { "Settings_JavaPath", "Путь" },
        { "Settings_JavaInvalid", "Не удалось добавить Java. Проверьте путь к файлу.\n\nУбедитесь, что выбранный файл является java.exe или javaw.exe" },
        { "Props_Loaded", "Свойства загружены" },
        { "Props_NotLoaded", "Ошибка: файл не загружен" },
        { "Props_Saved", "Свойства сохранены!" },
        { "Props_SaveError", "Ошибка сохранения" },
        { "Props_Reset", "Свойства сброшены" },
        { "ServerDetail_OperationError", "Не удалось выполнить операцию" },
        { "ServerDetail_PropsLoadError", "Ошибка загрузки свойств" },
        { "ServerDetail_ModsFolderNotFound", "Папка mods не найдена" },
        { "ServerDetail_PluginsFolderNotFound", "Папка plugins не найдена" },
        { "ServerDetail_DeleteModConfirm", "Удалить мод \"{0}\"?\n\nФайл: {1}" },
        { "ServerDetail_DeleteModTitle", "Удаление мода" },
        { "ServerDetail_DeletePluginConfirm", "Удалить плагин \"{0}\"?\n\nФайл: {1}" },
        { "ServerDetail_DeletePluginTitle", "Удаление плагина" },
        { "ServerDetail_ModDeleteError", "Ошибка удаления мода" },
        { "ServerDetail_ModToggleError", "Не удалось переключить мод" },
        { "ServerDetail_PluginDeleteError", "Ошибка удаления плагина" },
        { "ServerDetail_PluginToggleError", "Не удалось переключить плагин" },
        { "ServerDetail_DeleteServerError", "Ошибка при удалении сервера" },
        { "ServerDetail_JavaDefault", "По умолчанию" },
        { "ServerDetail_JavaNotSelected", "не выбрана" },
        { "App_StartupError", "Ошибка инициализации приложения" },
        { "App_StartupErrorDetail", "Проверьте логи в %AppData%\\Konserva\\Logs" },
        { "App_UnhandledError", "Необработанное исключение" },
        { "App_UnhandledErrorDetail", "Приложение будет закрыто." },
        { "Settings_Download", "Загрузки" },
        { "Settings_DownloadSource", "Источник скачивания" },
        { "Settings_DownloadSource_Desc", "Откуда скачивать файлы модлоадеров и игры" },
        { "Settings_DownloadSource_VanillaApi", "Официальный API Minecraft" },
        { "Settings_DownloadSource_BMCLAPI", "BMCLAPI (зеркало, быстрее в Китае/России)" },
        { "ServerDetail_Upnp", "UPnP проброс порта" },
        { "ServerDetail_Upnp_Enable", "Авто-проброс порта (UPnP)" },
        { "ServerDetail_Upnp_Enable_Desc", "Автоматически открывать порт сервера через UPnP при запуске" },
        { "ServerDetail_Upnp_Check", "Проверить UPnP" },
        { "ServerDetail_Upnp_Checking", "Проверка..." },
        { "ServerDetail_Upnp_Available", "UPnP доступен ✓" },
        { "ServerDetail_Upnp_NotAvailable", "UPnP недоступен (отключён на роутере?)" },
        { "ServerDetail_Upnp_CheckPort", "Проверить порт" },
        { "ServerDetail_Upnp_Port_Open", "Порт открыт" },
        { "ServerDetail_Upnp_Port_Closed", "Порт закрыт" },
        { "ServerDetail_Upnp_CopyAddress", "Копировать" },
        { "ServerDetail_Settings_RunningWarning", "Некоторые настройки нельзя изменить пока сервер запущен" },
        { "ServerDetail_Settings_RenameError", "Не удалось переименовать папку сервера: {0}" },
        { "ServerDetail_Settings_RenameSuccess", "Папка сервера переименована в \"{0}\"" },
    };
}
