using System.Collections.Generic;

namespace Konserva.Localization;

public static class RussianStrings
{
    public static readonly Dictionary<string, string> Translations = new Dictionary<string, string>
    {
        { "MainWindow_Title", "Konserva — Менеджер серверов Minecraft" },
        { "MainWindow_Servers", "Серверы" },
        { "MainWindow_Settings", "Настройки" },
        { "MainWindow_Header", "Konserva Manager" },
        { "StatusBar_TotalServers", "Всего серверов" },
        { "StatusBar_Running", "Запущено" },
        { "StatusBar_Memory", "Память" },
        { "StatusBar_Java_Configured", "Java настроена" },
        { "StatusBar_Java_NotConfigured", "Java не настроена" },
        { "StatusBar_Version", "Версия" },
        { "MainWindow_JavaVersions", "версии Java" },
        { "MainWindow_Error", "Ошибка" },
        { "Update_Available", "Доступна v{0}" },
        { "Update_Button", "Обновить" },
        { "Update_Downloading", "Загрузка..." },
        { "Update_Installing", "Установка..." },
        { "Update_Success", "Перезапуск..." },
        { "Update_Failed", "Ошибка обновления" },
        { "Update_Retry", "Повторить" },
        { "Update_Available_Tooltip", "Нажмите для обновления" },
        { "Update_Failed_Tooltip", "Ошибка обновления. Нажмите для повтора." },
        { "Settings_CheckForUpdates", "Проверить обновления" },
        { "Settings_UpToDate", "Установлена актуальная версия" },
        { "Settings_UpToDate_Button", "Актуальная версия" },
        { "Settings_UpdateAvailable_Button", "Доступно обновление {0}" },
        { "Settings_UpdateCheckError", "Ошибка проверки обновлений" },
        { "Settings_Title", "Настройки" },
        { "Settings_Servers", "Серверы" },
        { "Settings_Servers_Dir", "Папка серверов" },
        { "Settings_Servers_DirDesc", "Где будет создан сервер" },
        { "Settings_Servers_Browse", "Обзор" },
        { "Settings_Java", "Java" },
        { "Settings_Java_Empty", "Ни одной Java не установлено!" },
        { "Settings_Java_Add", "Добавить Java" },
        { "Settings_Java_Delete", "Удалить" },
        { "Settings_Java_Delete_Confirm_Title", "Удалить Java?" },
        { "Settings_Java_Delete_Confirm_Message", "Вы уверены, что хотите удалить эту установку Java?" },
        { "Settings_Java_Delete_Failed", "Не удалось удалить Java" },
        { "Settings_RAM_Min", "Память и приложение" },
        { "Settings_RAM_Min_Label", "Мин. ОЗУ (МБ)" },
        { "Settings_RAM_Max_Label", "Макс. ОЗУ (МБ)" },
        { "Settings_RAM_Min_Desc", "Начальный объем памяти" },
        { "Settings_RAM_Max_Desc", "Максимальный объем памяти" },
        { "Settings_App", "Приложение" },
        { "Settings_CheckUpdates", "Проверка обновлений" },
        { "Settings_CheckUpdates_Desc", "Автоматически проверять обновления" },
        { "Settings_CheckUpdates_OnLaunch", "При запуске" },
        { "Settings_CheckUpdates_Scheduled", "Заданное время" },
        { "Settings_CheckUpdates_Interval", "Интервал проверки" },
        { "Settings_CheckUpdates_Interval_Desc", "Как часто проверять обновления" },
        { "Settings_MinimizeToTray", "Сворачивать в трей" },
        { "Settings_MinimizeToTray_Desc", "Сворачивать в системный трей при закрытии окна вместо выхода" },
        { "Settings_ShowTrayIcon", "Иконка в трее" },
        { "Settings_ShowTrayIcon_Desc", "Всегда показывать иконку в трее, даже когда окно открыто.\nЕсли выключено — иконка только при свёрнутом окне" },
        { "Settings_Appearance", "Внешний вид" },
        { "Settings_Theme", "Тема" },
        { "Settings_Theme_Desc", "Выберите тему приложения" },
        { "Settings_Theme_System", "Как в системе" },
        { "Settings_Theme_Dark", "Тёмная" },
        { "Settings_Theme_Light", "Светлая" },
        { "Settings_Language", "Язык" },
        { "Settings_Language_Desc", "Выберите язык приложения" },
        { "Settings_Language_System", "Как в системе" },
        { "Settings_Language_System_Auto", "(авто)" },
        { "Settings_Language_English", "Английский" },
        { "Settings_Language_Russian", "Русский" },
        { "Settings_About", "О программе" },
        { "Settings_About_Version", "Версия" },
        { "Settings_About_Description", "Менеджер серверов Minecraft" },
        { "Settings_About_ModalLoaders", "Поддерживаемые модлоадеры:" },
        { "Settings_About_InDevelopment", "В разработке" },
        { "Message_SettingsSaved", "Настройки сохранены" },
        { "CreateServer_Title", "Создать сервер" },
        { "CreateServer_Name", "Название сервера" },
        { "CreateServer_MinecraftVersion", "Версия Minecraft" },
        { "CreateServer_ModLoader", "Модлоадер" },
        { "CreateServer_ModLoaderVersion", "Версия модлоадера" },
        { "CreateServer_Folder", "Папка" },
        { "CreateServer_browse", "Обзор" },
        { "CreateServer_Create", "Создать" },
        { "CreateServer_Browse", "Обзор" },
        { "CreateServer_Cancel", "Отмена" },
        { "CreateServer_Filter_Stable", "Показывать тестовые версии" },
        { "CreateServer_Not_Found", "Не найдено" },
        { "CreateServer_Import", "Импортировать" },
        { "CreateServer_Error_DialogLoad", "Ошибка загрузки диалога" },
        { "CreateServer_Import_Duplicate", "Сервер из этой папки уже импортирован:\n{0}" },
        { "CreateServer_Import_NoJar", "В выбранной папке не найден JAR файл сервера." },
        { "CreateServer_Import_Success", "Сервер \"{0}\" успешно импортирован!" },
        { "CreateServer_Import_Success_Title", "Импорт завершён" },
        { "CreateServer_Import_Error", "Ошибка импорта сервера" },
        { "CreateServer_Error_NoName", "Введите имя сервера" },
        { "CreateServer_Error_NoFolder", "Выберите папку для сервера" },
        { "CreateServer_Error_NoServerManager", "ServerManager не инициализирован!" },
        { "CreateServer_Validation_NoName", "Введите название сервера" },
        { "CreateServer_Validation_NoLoaderVersion", "Выберите версию модлоадера" },
        { "CreateServer_Validation_NoFolder", "Выберите папку сервера" },
        { "CreateServer_Error_DuplicateName", "Сервер с именем \"{0}\" уже существует. Пожалуйста, выберите другое имя." },
        { "CreateServer_Error_CreateFailed", "Ошибка при создании сервера" },
        { "CreateServer_Error_InstallFailed", "Не удалось установить сервер" },
        { "CreateServer_Error_InstallFailed_Exception", "Ошибка при установке сервера" },
        { "CreateServer_Browse_Title", "Выберите папку для сервера" },
        { "CreateServer_Import_Title", "Выберите папку с сервером" },
        { "CreateServer_Installing_Preparing", "Подготовка..." },
        { "CreateServer_Installing_Progress", "Установка {0}..." },
        { "CreateServer_Install_Error", "Ошибка: {0}" },
        { "CreateServer_Install_Cancelled", "Отменено" },
        { "CreateServer_Install_Ready", "Готов" },
        { "CreateServer_Validation_PathEmpty", "Путь к серверу не может быть пустым" },
        { "CreateServer_Validation_InvalidChars", "Путь содержит недопустимые символы" },
        { "CreateServer_Validation_PathTooLong", "Путь слишком длинный (максимум {0} символов)" },
        { "CreateServer_Validation_FileNotFolder", "Указанный путь является файлом, а не папкой" },
        { "CreateServer_Validation_SystemFolder", "Нельзя создавать серверы в системных папках Windows" },
        { "CreateServer_Validation_FolderNotEmpty", "Папка не пуста ({0} файлов). Убедитесь, что это правильное место для сервера." },
        { "CreateServer_Validation_ParentNotFound", "Родительская папка не существует" },
        { "CreateServer_Validation_NoPermission", "Недостаточно прав для создания папки" },
        { "CreateServer_Validation_Error", "Ошибка валидации пути: {0}" },
        { "ServersPage_Search", "Поиск..." },
        { "ServersPage_Filter_All", "Все типы" },
        { "ServersPage_Filter_AllServers", "Все серверы" },
        { "ServersPage_Filter_Running", "Запущен" },
        { "ServersPage_Filter_Stopped", "Остановлен" },
        { "ServersPage_SortBy", "Сортировка" },
        { "ServersPage_Sort_Header", "Сортировать по" },
        { "ServersPage_Sort_Name", "Названию" },
        { "ServersPage_Sort_Status", "Статусу" },
        { "ServersPage_Sort_Type", "Типу" },
        { "ServersPage_Sort_Version", "Версии" },

        { "ServersPage_Filter_Status", "Статус" },
        { "ServersPage_Create", "Создать сервер" },
        { "ServersPage_Port", "Порт:" },
        { "ServersPage_OpenFolder", "Открыть папку сервера" },
        { "ServersPage_Delete", "Удалить сервер" },
        { "ServersPage_NoServers", "Нет серверов" },
        { "ServersPage_NoServers_Description", "Создайте первый сервер для управления" },
        { "ServersPage_Error_AppNotInitialized", "Ошибка: приложение не инициализировано" },
        { "Common_Cancel", "Отмена" },
        { "Common_Copied", "Скопировано!" },
        { "Common_OK", "ОК" },
        { "Common_Yes", "Да" },
        { "Common_No", "Нет" },
        { "Common_Loading", "Загрузка..." },
        { "Common_None", "Нет" },
        { "Common_InDevelopment", "В разработке" },
        { "MsgBtn_OK", "ОК" },
        { "MsgBtn_Yes", "Да" },
        { "MsgBtn_No", "Нет" },
        { "MsgBtn_Cancel", "Отмена" },
        { "MsgBtn_Delete", "Удалить" },
        { "UiHelper_OpenFolderError", "Не удалось открыть папку" },
        { "MsgTitle_Info", "Информация" },
        { "MsgTitle_Warning", "Предупреждение" },
        { "MsgTitle_Error", "Ошибка" },
        { "MsgTitle_Confirm", "Подтверждение" },
        { "MsgTitle_DeleteServer", "Удаление сервера" },
        { "MsgInfo_Title", "Информация" },
        { "MsgWarning_Title", "Предупреждение" },
        { "MsgError_Title", "Ошибка" },
        { "MsgConfirm_Title", "Подтверждение" },
        { "MsgDel_Title", "Удаление сервера" },
        { "MsgDel_Confirm", "Вы уверены, что хотите удалить сервер \"{0}\"?" },
        { "MsgDel_WillBeDeleted", "Будут удалены:" },
        { "MsgDel_ServerFiles", "Все файлы сервера" },
        { "MsgDel_ConfigFiles", "Конфигурационные файлы" },
        { "MsgDel_WorldSaves", "Мир и сохранения" },
        { "MsgDel_LogsBackups", "Логи и бэкапы" },
        { "MsgDel_Irreversible", "Это действие необратимо!" },
        { "ServerDetail_Title", "Детали сервера" },
        { "ServerDetail_Console", "Консоль" },
        { "ServerDetail_Properties", "Файл server.properties" },
        { "ServerDetail_Settings", "Настройки сервера" },
        { "ServerDetail_Mods", "Моды" },
        { "ServerDetail_Plugins", "Плагины" },
        { "ServerDetail_Start", "Запустить" },
        { "ServerDetail_Stop", "Остановить" },
        { "ServerDetail_StartStop", "Запустить/Остановить" },
        { "ServerDetail_Starting", "Запускается..." },
        { "ServerDetail_Stopping", "Останавливается..." },
        { "ServerStatus_Stopped", "Остановлен" },
        { "ServerStatus_Running", "Запущен" },
        { "ServerStatus_Error", "Ошибка" },
        { "ServerDetail_Delete", "Удалить" },
        { "ServerDetail_OpenFolder", "Открыть папку" },
        { "ServerDetail_autoRestart", "Авто-рестарт" },
        { "ServerDetail_Java", "Java" },
        { "ServerDetail_RAM", "ОЗУ" },
        { "ServerDetail_Port", "Порт" },
        { "ServerDetail_Name", "Название" },
        { "ServerDetail_Version", "Версия" },
        { "ServerDetail_ModLoader", "Модлоадер" },
        { "ServerDetail_Status", "Статус" },
        { "ServerDetail_Status_Running", "Запущен" },
        { "ServerDetail_Status_Stopped", "Остановлен" },
        { "ServerDetail_Console_Empty", "Консоль пуста, запустите сервер" },
        { "ServerDetail_SendCommand", "Отправить" },
        { "ServerDetail_Mods_List", "Список модов" },
        { "ServerDetail_Mods_OpenFolder", "Открыть папку mods" },
        { "ServerDetail_Mods_Refresh", "Обновить" },
        { "ServerDetail_Mods_Delete", "Удалить" },
        { "ServerDetail_Mods_Toggle", "Вкл/Выкл" },
        { "ServerDetail_Mods_Enable", "Включить" },
        { "ServerDetail_Mods_Disable", "Отключить" },
        { "ServerDetail_Mods_ToggleAll", "Вкл/Выкл все" },
        { "ServerDetail_Mods_ToggleAll_Enable", "Включить все моды" },
        { "ServerDetail_Mods_ToggleAll_Disable", "Отключить все моды" },
        { "ServerDetail_Plugins_List", "Список плагинов" },
        { "ServerDetail_Plugins_OpenFolder", "Открыть папку plugins" },
        { "ServerDetail_Plugins_Refresh", "Обновить" },
        { "ServerDetail_Plugins_Delete", "Удалить" },
        { "ServerDetail_Plugins_Toggle", "Вкл/Выкл" },
        { "ServerDetail_Plugins_Enable", "Включить" },
        { "ServerDetail_Plugins_Disable", "Отключить" },
        { "ServerDetail_Plugins_ToggleAll", "Вкл/Выкл все" },
        { "ServerDetail_Plugins_ToggleAll_Enable", "Включить все плагины" },
        { "ServerDetail_Plugins_ToggleAll_Disable", "Отключить все плагины" },
        { "ServerProperties_Title", "Свойства сервера" },
        { "ServerProperties_Save", "Сохранить" },
        { "ServerProperties_Cancel", "Отмена" },
        { "ServerProperties_FileNotCreated", "Файл server.properties ещё не создан" },
        { "ServerProperties_FileNotCreated_Hint", "Файл создастся автоматически при первом запуске сервера" },
        { "ServerProperties_General", "Основные" },
        { "ServerProperties_ServerPort", "Порт сервера" },
        { "ServerProperties_ServerPort_Desc", "Должен быть открыт для сети" },
        { "ServerProperties_ServerIp", "IP сервера" },
        { "ServerProperties_ServerIp_Desc", "Меняйте, если только знаете что делаете" },
        { "ServerProperties_MaxPlayers", "Макс. игроков" },
        { "ServerProperties_MaxPlayers_Desc", "Макс. количество игроков на сервере" },
        { "ServerProperties_ViewDistance", "Дальность прорисовки" },
        { "ServerProperties_ViewDistance_Desc", "Видимость чанков клиеном" },
        { "ServerProperties_SimulationDistance", "Дальность симуляции" },
        { "ServerProperties_SimulationDistance_Desc", "Расстояние обновления мобов и процессов мира" },
        { "ServerProperties_MOTD", "MOTD" },
        { "ServerProperties_MOTD_Desc", "Описание для сервера" },
        { "ServerProperties_Gamemode", "Режим игры" },
        { "ServerProperties_Gamemode_Desc", "Режим по умолчанию для новых игроков" },
        { "ServerProperties_Gamemode_Survival", "Выживание" },
        { "ServerProperties_Gamemode_Creative", "Творчество" },
        { "ServerProperties_Gamemode_Adventure", "Приключение" },
        { "ServerProperties_Gamemode_Spectator", "Наблюдатель" },
        { "ServerProperties_Difficulty", "Сложность" },
        { "ServerProperties_Difficulty_Desc", "Чем выше сложность, тем сложнее" },
        { "ServerProperties_Difficulty_Peaceful", "Мирный" },
        { "ServerProperties_Difficulty_Easy", "Лёгкий" },
        { "ServerProperties_Difficulty_Normal", "Обычный" },
        { "ServerProperties_Difficulty_Hard", "Сложный" },
        { "ServerProperties_Hardcore", "Хардкор" },
        { "ServerProperties_Hardcore_Desc", "Смерть навсегда" },
        { "ServerProperties_PvP", "PvP" },
        { "ServerProperties_PvP_Desc", "Могут ли игроки атаковать друг друга" },
        { "ServerProperties_CommandBlocks", "Командные блоки" },
        { "ServerProperties_CommandBlocks_Desc", "Разрешает командные блоки в мире" },
        { "ServerProperties_World", "Мир" },
        { "ServerProperties_LevelName", "Имя мира" },
        { "ServerProperties_LevelName_Desc", "Имя папки с сохранением мира" },
        { "ServerProperties_LevelSeed", "Сид (seed)" },
        { "ServerProperties_LevelSeed_Desc", "Код генерации мира. Пусто = случайный" },
        { "ServerProperties_LevelType", "Тип мира" },
        { "ServerProperties_LevelType_Desc", "Тип генерации ландшафта" },
        { "ServerProperties_LevelType_Normal", "Обычный" },
        { "ServerProperties_LevelType_Flat", "Плоский" },
        { "ServerProperties_LevelType_LargeBiomes", "Крупные биомы" },
        { "ServerProperties_LevelType_Amplified", "Амплифицированный" },
        { "ServerProperties_LevelType_SingleBiome", "Один биом" },
        { "ServerProperties_MaxWorldSize", "Макс. размер мира" },
        { "ServerProperties_MaxWorldSize_Desc", "Макс. радиус мира в блоках" },
        { "ServerProperties_SpawnStructures", "Генерация структур" },
        { "ServerProperties_SpawnStructures_Desc", "Деревни, храмы, крепости и другие постройки" },
        { "ServerProperties_AllowNether", "Доступ в Нижний мир" },
        { "ServerProperties_AllowNether_Desc", "Разрешить портал в Нижний мир" },
        { "ServerProperties_Network", "Сеть" },
        { "ServerProperties_OnlineMode", "Проверка лицензии" },
        { "ServerProperties_OnlineMode_Desc", "Отключите для пиратских клиентов" },
        { "ServerProperties_Whitelist", "Белый список" },
        { "ServerProperties_Whitelist_Desc", "Только игроки из списка смогут зайти на сервер" },
        { "ServerProperties_EnforceWhitelist", "Принудительный белый список" },
        { "ServerProperties_EnforceWhitelist_Desc", "Кикать игроков, удалённых из белого списка" },
        { "ServerProperties_EnforceSecureProfile", "Безопасный профиль" },
        { "ServerProperties_EnforceSecureProfile_Desc", "Требовать от клиентов подписанный профиль" },
        { "ServerProperties_AllowFlight", "Разрежить полёты" },
        { "ServerProperties_AllowFlight_Desc", "Разрешить полёт для модов" },
        { "ServerProperties_RCON", "RCON" },
        { "ServerProperties_EnableRcon", "Включить RCON" },
        { "ServerProperties_EnableRcon_Desc", "Удалённое управление сервером по сети" },
        { "ServerProperties_RconPassword", "Пароль RCON" },
        { "ServerProperties_RconPassword_Desc", "Пароль для подключения к RCON" },
        { "ServerProperties_RconPort", "Порт RCON" },
        { "ServerProperties_RconPort_Desc", "Порт для RCON-подключений" },
        { "ServerProperties_RconIp", "IP RCON" },
        { "ServerProperties_RconIp_Desc", "IP для RCON. По умолч. = все интерфейсы" },
        { "ServerProperties_Permissions", "Разрешения" },
        { "ServerProperties_SpawnProtection", "Защита спавна" },
        { "ServerProperties_SpawnProtection_Desc", "Радиус защиты вокруг спавна. 0 = отключить" },
        { "ServerProperties_SpawnNPCs", "Спавн NPC" },
        { "ServerProperties_SpawnNPCs_Desc", "Появление жителей деревень" },
        { "ServerProperties_SpawnAnimals", "Спавн животных" },
        { "ServerProperties_SpawnAnimals_Desc", "Появление коров, свиней и других животных" },
        { "ServerProperties_SpawnMonsters", "Спавн монстров" },
        { "ServerProperties_SpawnMonsters_Desc", "Появление зомби, скелетов и криперов" },
        { "ServerProperties_SpawnRadius", "Радиус спавна" },
        { "ServerProperties_SpawnRadius_Desc", "Появление игрока относительно точки спавна" },
        { "ServerProperties_OpPermissionLevel", "Уровень прав OP" },
        { "ServerProperties_OpPermissionLevel_Desc", "Уровень доступа оператора" },
        { "ServerProperties_EnableStatus", "Включить статус" },
        { "ServerProperties_EnableStatus_Desc", "Показывать статус сервера в списке серверов" },
        { "ServerProperties_ForceGamemode", "Принудительный режим" },
        { "ServerProperties_ForceGamemode_Desc", "Заставить игроков использовать режим сервера" },
        { "ServerProperties_GeneratorSettings", "Настройки генератора" },
        { "ServerProperties_GeneratorSettings_Desc", "Параметры генерации мира (JSON)" },
        { "ServerProperties_NetworkCompression", "Сжатие сети" },
        { "ServerProperties_NetworkCompression_Desc", "Порог сжатия пакетов" },
        { "ServerProperties_MaxTickTime", "Макс. время тика" },
        { "ServerProperties_MaxTickTime_Desc", "Макс. время тика в мс (-1 = отключено)" },
        { "ServerProperties_PreventProxyConnections", "Блокировка прокси" },
        { "ServerProperties_PreventProxyConnections_Desc", "Предотвращать подключения через прокси" },
        { "ServerProperties_RateLimit", "Ограничение скорости" },
        { "ServerProperties_RateLimit_Desc", "Макс. пакетов в секунду (0 = без ограничений)" },
        { "ServerProperties_PlayerIdleTimeout", "Таймаут бездействия" },
        { "ServerProperties_PlayerIdleTimeout_Desc", "Кикать после X минут бездействия (0 = отключить)" },
        { "ServerProperties_AcceptsTransfers", "Принимать трансферы" },
        { "ServerProperties_AcceptsTransfers_Desc", "Принимать трансферы миров с других серверов" },
        { "ServerProperties_StatusHeartbeatInterval", "Интервал heartbeat" },
        { "ServerProperties_StatusHeartbeatInterval_Desc", "Интервал отправки статуса (0 = по умолчанию)" },
        { "ServerProperties_HideOnlinePlayers", "Скрыть игроков" },
        { "ServerProperties_HideOnlinePlayers_Desc", "Скрыть список игроков из статуса сервера" },
        { "ServerProperties_WhitelistSection", "Белый список" },
        { "ServerProperties_Query", "Query" },
        { "ServerProperties_EnableQuery", "Включить Query" },
        { "ServerProperties_EnableQuery_Desc", "Протокол запроса информации о сервере (GameSpy 4)" },
        { "ServerProperties_QueryPort", "Query порт" },
        { "ServerProperties_QueryPort_Desc", "Порт для Query запросов" },
        { "ServerProperties_FunctionPermissionLevel", "Уровень прав функций" },
        { "ServerProperties_FunctionPermissionLevel_Desc", "Макс. уровень для выполнения функций (1–4)" },
        { "ServerProperties_EnabledPacks", "Включённые датапаки" },
        { "ServerProperties_EnabledPacks_Desc", "Список включённых датапаков, через запятую" },
        { "ServerProperties_DisabledPacks", "Отключённые датапаки" },
        { "ServerProperties_DisabledPacks_Desc", "Список отключённых датапаков, через запятую" },
        { "ServerProperties_ManagementServer", "Сервер управления" },
        { "ServerProperties_ManagementServerEnabled", "Включить сервер управления" },
        { "ServerProperties_ManagementServerEnabled_Desc", "Включить API сервера ��правления" },
        { "ServerProperties_ManagementServerHost", "Хост управления" },
        { "ServerProperties_ManagementServerHost_Desc", "Привязка API сервера управления" },
        { "ServerProperties_ManagementServerPort", "Порт управления" },
        { "ServerProperties_ManagementServerPort_Desc", "Порт API сервера управления" },
        { "ServerProperties_ManagementServerSecret", "Секрет управления" },
        { "ServerProperties_ManagementServerSecret_Desc", "Секретный ключ для API" },
        { "ServerProperties_ManagementServerTlsEnabled", "TLS для управления" },
        { "ServerProperties_ManagementServerTlsEnabled_Desc", "Включить TLS для API" },
        { "ServerProperties_ManagementServerTlsKeystore", "Keystore TLS" },
        { "ServerProperties_ManagementServerTlsKeystore_Desc", "Путь к файлу keystore" },
        { "ServerProperties_ManagementServerAllowedOrigins", "Разрешённые origins" },
        { "ServerProperties_ManagementServerAllowedOrigins_Desc", "Разрешённые CORS origins" },
        { "ServerProperties_ResourcePack", "Набор ресурсов" },
        { "ServerProperties_ResourcePackUrl", "URL набора ресурсов" },
        { "ServerProperties_ResourcePackUrl_Desc", "Ссылка для скачивания набора ресурсов" },
        { "ServerProperties_ResourcePackSha1", "SHA1 набора ресурсов" },
        { "ServerProperties_ResourcePackSha1_Desc", "SHA1 хэш набора ресурсов" },
        { "ServerProperties_ResourcePackId", "ID набора ресурсов" },
        { "ServerProperties_ResourcePackId_Desc", "Индетификатор набора ресурсов" },
        { "ServerProperties_ResourcePackPrompt", "Подсказка набора ресурсов" },
        { "ServerProperties_ResourcePackPrompt_Desc", "Текст подсказки при запросе набора ресурсов" },
        { "ServerProperties_RequireResourcePack", "Требовать набор ресурсов" },
        { "ServerProperties_RequireResourcePack_Desc", "Обязательная загрузка набора ресурсов" },
        { "ServerProperties_MaxChainedNeighborUpdates", "Обновления соседей" },
        { "ServerProperties_MaxChainedNeighborUpdates_Desc", "Макс. цепных обновлений соседей (-1 = без ограничений)" },
        { "ServerProperties_EntityBroadcastRangePercentage", "Дальность сущностей" },
        { "ServerProperties_EntityBroadcastRangePercentage_Desc", "% дальности рассылки о сущностях" },
        { "ServerProperties_SyncChunkWrites", "Синхр. записи чанков" },
        { "ServerProperties_SyncChunkWrites_Desc", "Синхронизировать запись чанков" },
        { "ServerProperties_UseNativeTransport", "Нативный транспорт" },
        { "ServerProperties_UseNativeTransport_Desc", "Использовать нативную поддержку Linux" },
        { "ServerProperties_Logging", "Логирование" },
        { "ServerProperties_LogIps", "Логировать IP" },
        { "ServerProperties_LogIps_Desc", "Записывать IP-адреса в лог" },
        { "ServerProperties_BroadcastConsoleToOps", "Консоль → OPS" },
        { "ServerProperties_BroadcastConsoleToOps_Desc", "Отправлять сообщения консоли операторам" },
        { "ServerProperties_BroadcastRconToOps", "RCON → OPS" },
        { "ServerProperties_BroadcastRconToOps_Desc", "Отправлять сообщения RCON операторам" },
        { "ServerProperties_EnableJmxMonitoring", "JMX мониторинг" },
        { "ServerProperties_EnableJmxMonitoring_Desc", "Включить мониторинг через JMX" },
        { "ServerProperties_EnableCodeOfConduct", "Кодекс поведения" },
        { "ServerProperties_EnableCodeOfConduct_Desc", "Включить применение кодекса поведения" },
        { "ServerProperties_BugReportLink", "Ссылка на баг-репорт" },
        { "ServerProperties_BugReportLink_Desc", "URL для отправки баг-репортов" },
        { "ServerProperties_PauseWhenEmptySeconds", "Пауза при пустом сервере" },
        { "ServerProperties_PauseWhenEmptySeconds_Desc", "Секунды до паузы при отсутствии игроков" },
        { "ServerProperties_RegionFileCompression", "Сжатие файлов регионов" },
        { "ServerProperties_RegionFileCompression_Desc", "Алгоритм сжатия файлов мира" },
        { "ServerProperties_RegionFileCompression_Deflate", "Deflate (Zlib)" },
        { "ServerProperties_RegionFileCompression_Lz4", "LZ4" },
        { "ServerProperties_TextFilteringConfig", "Конфиг текстового фильтра" },
        { "ServerProperties_TextFilteringConfig_Desc", "Путь к файлу конфигурации фильтра текста" },
        { "ServerProperties_TextFilteringVersion", "Версия текстового фильтра" },
        { "ServerProperties_TextFilteringVersion_Desc", "Версия фильтра для обновления конфига" },
        { "ServerProperties_ManagementServerTlsKeystorePassword", "Пароль keystore TLS" },
        { "ServerProperties_ManagementServerTlsKeystorePassword_Desc", "Пароль для keystore TLS" },
        { "ServerProperties_Deprecated", "Устаревшие настройки" },
        { "ServerProperties_Performance", "Производительность" },
        { "ServerProperties_Gameplay", "Геймплей" },
        { "ServerProperties_Reset", "Сбросить" },
        { "ServerProperties_Refresh", "Обновить" },
        { "ServerDetail_Settings_General", "Название сервера" },
        { "ServerDetail_Settings_General_Desc", "Название сервера в приложении" },
        { "ServerDetail_Settings_Port", "Порт" },
        { "ServerDetail_Settings_Port_Desc", "Порт для сервера" },
        { "ServerDetail_Settings_RAM", "Выделение памяти" },
        { "ServerDetail_Settings_RAM_Min", "Минимум ОЗУ (МБ)" },
        { "ServerDetail_Settings_RAM_Min_Desc", "Минимальный размер памяти для сервера" },
        { "ServerDetail_Settings_RAM_Max", "Максимум ОЗУ (МБ)" },
        { "ServerDetail_Settings_RAM_Max_Desc", "Максимальный размер памяти для сервера" },
        { "ServerDetail_Settings_AutoRestart", "Автоперезапуск" },
        { "ServerDetail_Settings_AutoRestart_Enable", "Включить автоперезапуск сервера" },
        { "ServerDetail_Settings_AutoRestart_Desc", "Автоматически перезапускать сервер при остановке" },
        { "ServerDetail_Settings_AutoRestart_Delay", "Задержка перед перезапуском (сек.)" },
        { "ServerDetail_Settings_AutoRestart_Delay_Desc", "Задержка перед автоматическим перезапуском" },
        { "ServerDetail_Settings_Java_Auto", "Автовыбор версии Java" },
        { "ServerDetail_Settings_Java_Auto_Desc", "Автоматически выбирать Java на основе версии Minecraft" },
        { "ServerDetail_Settings_Java_Version", "Версия Java" },
        { "ServerDetail_Settings_JvmArgs", "JVM аргументы" },
        { "ServerDetail_Settings_JvmArgs_Desc", "По одному аргументу на строку. Можно безопасно изменять и удалять." },
        { "Log_ServerStarted", "Сервер полностью загрузился" },
        { "Log_JavaVersionMismatch", "НЕСОВМЕСТИМОСТЬ ВЕРСИИ JAVA!" },
        { "Log_JavaVersionMismatch_Detail", "Для Minecraft {0} требуется Java {1} или выше" },
        { "Log_JavaFound", "Найдена Java: {0} (версия {1})" },
        { "Log_JavaPath", "Путь к Java: {0}" },
        { "Log_Solution", "Решение:" },
        { "Log_Solution_Install_Java", "1. Установите Java {0}: https://adoptium.net/" },
        { "Log_Solution_Add_Java", "2. Укажите путь к Java {0} в настройках приложения" },
        { "Log_Solution_Older_Minecraft", "3. Или выберите более старую версию Minecraft" },
        { "Log_JavaNotFound", "JAVA НЕ НАЙДЕНА!" },
        { "Log_JavaNotFound_Path", "Путь к Java: {0}" },
        { "Log_JavaNotFound_Error", "Ошибка: {0}" },
        { "Log_Solution_Install_Java_General", "1. Установите Java: https://adoptium.net/" },
        { "Log_Solution_Add_Java_Settings", "2. Добавьте Java в настройках приложения (кнопка 'Добавить Java')" },
        { "Log_Solution_Check_PATH", "3. Убедитесь, что Java добавлена в PATH" },
        { "Log_CriticalError", "Критическая ошибка запуска!" },
        { "Log_ErrorType", "Тип: {0}" },
        { "Log_ErrorMessage", "Сообщение: {0}" },
        { "Log_ErrorOutput", "Вывод ошибки: {0}" },
        { "Log_ServerStoppedWithCode", "Сервер завершился с кодом ошибки: {0}" },
        { "Log_ServerConfigProblem", "Это может означать проблему с конфигурацией" },
        { "Log_MemoryProblem", "или нехватку памяти." },
        { "Log_TimeoutForceKill", "Таймаут остановки, принудительное завершение..." },
        { "Log_ForceKillAttempt", "Попытка принудительного завершения..." },
        { "Log_ServerNotRunning", "Попытка отправки команды на остановленный сервер: {0}" },
        { "Log_JavaFromSettingsNotFound", "Java из настроек сервера не найдена: {0}" },
        { "Log_JavaVersionNotFound_TryDefault", "Не найдена Java {0}+, пробуем Java по умолчанию" },
        { "Log_JavaDefaultNotFound", "Java по умолчанию не найдена: {0}" },
        { "Log_UsingJavaFromPATH", "Используем Java из PATH" },
        { "Log_ServerId", "ID сервера: {0}" },
        { "Log_ModLoader", "Модлоадер: {0} {1}" },
        { "Log_MinecraftVersion", "Версия Minecraft: {0}" },
        { "Log_ServerFolder", "Папка сервера: {0}" },
        { "Log_LaunchType", "Тип запуска: {0}" },
        { "Log_JarFile", "JAR файл: {0} ({1} MB)" },
        { "Log_JavaVersion", "Java версия: {0}" },
        { "Log_JavaPath_Info", "Java путь: {0}" },
        { "Log_JavaArgs", "Аргументы Java: {0}" },
        { "Log_WorkingDirectory", "Рабочая директория: {0}" },
        { "Log_LaunchingProcess", "Запуск процесса..." },
        { "Log_WaitingForStartup", "Ожидание запуска сервера..." },
        { "Log_LaunchCancelled", "Запуск отменён" },
        { "Log_EulaAccepted", "EULA принята" },
        { "Log_JavaVersionCompatible", "Версия Java совместима (требуется {0}+)" },
        { "Log_ProcessStarted", "Процесс запущен, PID: {0}" },
        { "Log_LaunchForceCancelled", "Запуск отменён принудительно" },
        { "Log_ProcessForceKilled", "Процесс завершён принудительно (сервер ещё не загрузился)" },
        { "Log_ExitError", "Ошибка завершения: {0}" },
        { "Log_StoppingWithCommand", "Остановка сервера • Отправка команды..." },
        { "Log_WaitingForProcessExit", "Ожидание завершения процесса (60 сек)..." },
        { "Log_ProcessForceKilledAfterTimeout", "Процесс завершен принудительно" },
        { "Log_ServerStoppedSuccessfully", "Сервер успешно остановлен" },
        { "Log_StopCancelled", "Остановка отменена" },
        { "Log_KillFailedOnCancel", "Не удалось завершить процесс при отмене: {0}" },
        { "Log_StopError", "Ошибка остановки: {0}" },
        { "Log_CommandSent", "> {0}" },
        { "Log_CommandSendError", "Ошибка отправки команды '{0}': {1}" },
        { "Log_OldLogDeleted", "Удалён старый лог: latest.log" },
        { "Log_LogMoved", "Перемещён заблокированный лог: latest.log -> {0}" },
        { "Log_CleanupFailed", "Не удалось очистить старые логи: {0}" },
        { "Log_ConfigUnavailable", "Конфигурация недоступна, используем Java из PATH" },
        { "Log_UsingServerJava", "Используем Java из настроек сервера: {0}" },
        { "Log_AutoSelectJava", "Автовыбор Java: требуется Java {0}+ для Minecraft {1}" },
        { "Log_JavaSelected", "Выбрана Java: {0}" },
        { "Log_UsingJava", "Используем Java: {0}" },
        { "Log_AutoRestart", "Авто-рестарт через" },
        { "Log_Seconds", "сек" },
        { "Log_ServerFullyLoaded", "Сервер полностью загрузился" },
        { "Log_ServerStarting", "Запуск сервера: {0}" },
        { "Log_KillFailed", "Не удалось завершить процесс: {0}" },
        { "Log_ServerStoppedCode0", "Сервер остановлен (код выхода: 0)" },
        { "Log_MonitorCancelled", "Мониторинг процесса отменён" },
        { "Log_MonitorError", "Ошибка мониторинга процесса: {0}" },
        { "Message_ConfirmDelete", "Вы уверены, что хотите удалить сервер?" },
        { "Message_Error", "Ошибка" },
        { "Message_DeleteMod", "Удалить" },
        { "Message_DeletePlugin", "Удалить" },
        { "Message_RestartRequired", "Для применения нового языка требуется перезапуск приложения." },
        { "Error_JavaNotFound", "Java не найдена" },
        { "Error_JavaIncompatible", "Несовместимая версия Java" },
        { "Error_ServerInstallFailed", "Ошибка установки сервера" },
        { "Error_PortInUse", "Порт уже занят" },
        { "Error_OutOfMemory", "Недостаточно памяти" },
        { "Snackbar_JavaIncompatible_Title", "Несовместимая Java" },
        { "Snackbar_JavaIncompatible_Message", "Для Minecraft {0} требуется Java {1}+, найдена Java {2}.\nСервер не запустится с текущей версией Java." },
        { "Snackbar_JavaIncompatible_Message_Plural", "Для Minecraft {0} требуется Java {1}+, найдены Java: {2}.\nСервер не запустится с текущими версиями Java." },
        { "JavaError_Title", "Ошибка Java" },
        { "JavaError_Required", "Требуется установить или обновить Java" },
        { "JavaError_DownloadText", "Скачайте последнюю версию Java с официального са��та:" },
        { "JavaError_DownloadBtn", "Скачать Java (adoptium.net)" },
        { "Common_NotSelected", "Не выбрано" },
        { "Common_Default", "По умолчанию" },
        { "Common_Unknown", "Неиз��естно" },
        { "Common_Preparing", "Подготовка..." },
        { "Settings_SelectServerFolder", "Выберите папку для серверов" },
        { "Settings_SelectJava", "Выберите java.exe или javaw.exe" },
        { "Settings_JavaFilter", "Java executable|java.exe|JavaW executable|javaw.exe" },
        { "Settings_JavaAdded", "Java добавлена" },
        { "Settings_JavaVersion", "Версия" },
        { "Settings_JavaPath", "Путь" },
        { "Settings_JavaInvalid", "Не удалось добавить Java. Проверьте путь к файлу.\n\nУбедитесь, что выбранный файл является java.exe или javaw.exe" },
        { "Props_Loaded", "Свойства загружены" },
        { "Props_NotLoaded", "Ошибка: файл не загружен" },
        { "Props_Saved", "Свойства сохранены!" },
        { "Props_SaveError", "Ошибка сохранения" },
        { "Props_Reset", "Свойства сброшены" },
        { "ServerDetail_OperationError", "Не удалось выполнить операцию" },
        { "ServerDetail_OpenFolderError", "Не удалось открыть папку сервера" },
        { "ServerDetail_PropsLoadError", "Ошибка загрузки свойств" },
        { "ServerDetail_ModsLoadError", "Ошибка загрузки модов" },
        { "ServerDetail_PluginsLoadError", "Ошибка загрузки плагинов" },
        { "ServerDetail_ModsFolderNotFound", "Папка mods не найдена" },
        { "ServerDetail_PluginsFolderNotFound", "Папка plugins не найдена" },
        { "ServerDetail_FolderOpenError", "Не удалось открыть папку" },
        { "ServerDetail_DeleteModConfirm", "Удалить мод \"{0}\"?\n\nФайл: {1}" },
        { "ServerDetail_DeleteModTitle", "Удаление мода" },
        { "ServerDetail_DeletePluginConfirm", "Удалить плагин \"{0}\"?\n\nФайл: {1}" },
        { "ServerDetail_DeletePluginTitle", "Удаление плагина" },
        { "ServerDetail_ModDeleteError", "Ошибка удаления мода" },
        { "ServerDetail_ModToggleError", "Не удалось переключить мод" },
        { "ServerDetail_PluginDeleteError", "Ошибка удаления плагина" },
        { "ServerDetail_PluginToggleError", "Не удалось переключить плагин" },
        { "ServerDetail_DeleteServerError", "Ошибка при удалении сервера" },
        { "ServerDetail_JavaDefault", "По умолчанию" },
        { "ServerDetail_JavaNotSelected", "не выбрана" },
        { "ServersPage_AppNotInitialized", "Ошибка: приложение не инициализировано" },
        { "ServersPage_OpenFolderWarning", "Не удалось открыть папку сервера" },
        { "ServersPage_DeleteError", "Ошибка при удалении сервера" },
        { "ServersPage_OperationError", "Не удалось выполнить операцию" },
        { "App_StartupError", "Ошибка инициализации приложения" },
        { "App_StartupErrorDetail", "Проверьте логи в %AppData%\\Konserva\\Logs" },
        { "App_UnhandledError", "Необработанное исключение" },
        { "App_UnhandledErrorDetail", "Приложение будет закрыто." },

        { "Settings_Download", "Загрузки" },
        { "Settings_DownloadSource", "Источник скачивания" },
        { "Settings_DownloadSource_Desc", "Откуда скачивать файлы модлоадеров и игры" },
        { "Settings_DownloadSource_VanillaApi", "Официальный API Minecraft" },
        { "Settings_DownloadSource_BMCLAPI", "BMCLAPI (зеркало, быстрее в Китае/России)" },

        { "ServerDetail_Upnp", "UPnP Проброс порта" },
        { "ServerDetail_Upnp_Enable", "Авто-проброс порта (UPnP)" },
        { "ServerDetail_Upnp_Enable_Desc", "Автоматически открывать порт сервера через UPnP при запуске" },
        { "ServerDetail_Upnp_Check", "Проверить UPnP" },
        { "ServerDetail_Upnp_Checking", "Проверка..." },
        { "ServerDetail_Upnp_Available", "UPnP доступен ✓" },
        { "ServerDetail_Upnp_NotAvailable", "UPnP недоступен (отключён на роутере?)" },
        { "ServerDetail_Upnp_Error", "Ошибка проверки UPnP" },
        { "ServerDetail_Upnp_Created", "Порт {0} открыт через UPnP" },
        { "ServerDetail_Upnp_Deleted", "Порт {0} закрыт через UPnP" },
        { "ServerDetail_Upnp_Failed", "Не удалось открыть порт через UPnP" },
        { "ServerDetail_Upnp_CheckPort", "Проверить порт" },
        { "ServerDetail_Upnp_Port_Open", "Порт открыт" },
        { "ServerDetail_Upnp_Port_Closed", "Порт закрыт" },
        { "ServerDetail_Upnp_ExternalIp", "Внешний IP: {0}" },
        { "ServerDetail_Upnp_Check_Desc", "Проверяет UPnP на роутере и открыт ли порт сервера. Для проверки порта сервер должен быть запущен с UPnP." },
        { "ServerDetail_Upnp_CopyAddress", "Копировать" },
    };
}