using System.IO;
using System.Text;

namespace Konserva.Models;

/// <summary>
/// Модель server.properties Minecraft сервера
/// </summary>
public class ServerProperties
{
    // Основные настройки
    public int ServerPort { get; set; } = 25565;
    public string Ip { get; set; } = "";
    public string ServerIp { get; set; } = "";
    public int MaxPlayers { get; set; } = 20;
    public int ViewDistance { get; set; } = 10;
    
    // Режимы игры
    public string Gamemode { get; set; } = "survival";
    public bool Hardcore { get; set; } = false;
    public string Difficulty { get; set; } = "easy"; // peaceful, easy, normal, hard
    public bool CommandBlocks { get; set; } = true;
    
    // Мир
    public string LevelName { get; set; } = "world";
    public string LevelSeed { get; set; } = "";
    public string LevelType { get; set; } = "minecraft:normal";
    public int MaxWorldSize { get; set; } = 29999984;
    public bool GenerateStructures { get; set; } = true;
    
    // Сложности
    public bool AllowNether { get; set; } = true;
    public bool AllowFlight { get; set; } = false;
    public int SpawnProtection { get; set; } = 16;
    public int SpawnRadius { get; set; } = 10;
    
    // Сеть
    public bool OnlineMode { get; set; } = true;
    public bool PreventProxyConnections { get; set; } = true;
    public int NetworkCompressionThreshold { get; set; } = 256;
    public int MaxTickTime { get; set; } = 60000;
    
    // RCON
    public bool EnableRcon { get; set; } = false;
    public string RconPassword { get; set; } = "";
    public int RconPort { get; set; } = 25575;
    public string RconIp { get; set; } = "";
    
    // Query
    public bool EnableQuery { get; set; } = false;
    public int QueryPort { get; set; } = 25565;
    
    // Прочее
    public bool WhiteList { get; set; } = false;
    public bool EnforceWhitelist { get; set; } = false;
    public bool EnforceSecureProfile { get; set; } = true;
    public string Motd { get; set; } = "A Minecraft Server";
    public int OpPermissionLevel { get; set; } = 4;
    public bool BroadcastConsoleToOps { get; set; } = true;
    public bool BroadcastRconToOps { get; set; } = true;
    public bool SyncChunkWrites { get; set; } = true;
    public bool UseNativeTransport { get; set; } = true;
    
    // Игнорируемые свойства (нечитаемые)
    public string LevelDat { get; set; } = "";
    public string ResourcePack { get; set; } = "";
    public bool RequireResourcePack { get; set; } = false;
    public string ResourcePackSha1 { get; set; } = "";
    public int SimulationDistance { get; set; } = 10;
    public bool HideOnlinePlayers { get; set; } = false;
    public int PlayerIdleTimeout { get; set; } = 0;
    public int MaxChainedNeighborUpdates { get; set; } = 1000000;
    public string InitialDisabledPacks { get; set; } = "";
    public string InitialEnabledPacks { get; set; } = "vanilla";
    public bool LogIp { get; set; } = true;
    public int RateLimit { get; set; } = 0;
    public bool ForceGamemode { get; set; } = false;
    public int EntityBroadcastRangePercentage { get; set; } = 100;
    public string FunctionPermissionLevel { get; set; } = "2";
    public string AoiList { get; set; } = "";
    
    // Удалено в 1.21.2+ (оставлено для совместимости)
    public bool Pvp { get; set; } = true;
    public bool SpawnNpcs { get; set; } = true;
    public bool SpawnAnimals { get; set; } = true;
    public bool SpawnMonsters { get; set; } = true;

    /// <summary>
    /// Загрузить свойства из файла
    /// </summary>
    public static ServerProperties Load(string path)
    {
        var props = new ServerProperties();
        
        if (!File.Exists(path))
            return props;

        var lines = File.ReadAllLines(path, Encoding.UTF8);
        
        foreach (var line in lines)
        {
            var trimmedLine = line.Trim();
            
            // Пропускаем комментарии и пустые строки
            if (string.IsNullOrEmpty(trimmedLine) || trimmedLine.StartsWith("#"))
                continue;

            var eqIndex = trimmedLine.IndexOf('=');
            if (eqIndex <= 0)
                continue;

            var key = trimmedLine[..eqIndex].Trim();
            var value = trimmedLine[(eqIndex + 1)..].Trim();

            SetProperty(props, key, value);
        }

        return props;
    }

    /// <summary>
    /// Сохранить свойства в файл
    /// </summary>
    public void Save(string path)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("#Minecraft server properties");
        sb.AppendLine($"#Generated by Konserva - {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        
        // Основные настройки
        sb.AppendLine("# ===== BASIC SETTINGS =====");
        sb.AppendLine($"server-port={ServerPort}");
        sb.AppendLine($"server-ip={ServerIp}");
        sb.AppendLine($"max-players={MaxPlayers}");
        sb.AppendLine($"view-distance={ViewDistance}");
        sb.AppendLine($"simulation-distance={SimulationDistance}");
        sb.AppendLine();
        
        // Режимы игры
        sb.AppendLine("# ===== GAME MODE =====");
        sb.AppendLine($"gamemode={Gamemode}");
        sb.AppendLine($"hardcore={Hardcore.ToString().ToLower()}");
        sb.AppendLine($"difficulty={Difficulty}");
        sb.AppendLine($"pvp={Pvp.ToString().ToLower()}");
        sb.AppendLine($"command-block-enabled={CommandBlocks.ToString().ToLower()}");
        sb.AppendLine();
        
        // Мир
        sb.AppendLine("# ===== WORLD SETTINGS =====");
        sb.AppendLine($"level-name={LevelName}");
        sb.AppendLine($"level-seed={LevelSeed}");
        sb.AppendLine($"level-type={LevelType}");
        sb.AppendLine($"max-world-size={MaxWorldSize}");
        sb.AppendLine($"generate-structures={GenerateStructures.ToString().ToLower()}");
        sb.AppendLine($"allow-nether={AllowNether.ToString().ToLower()}");
        sb.AppendLine();
        
        // Сложности
        sb.AppendLine("# ===== DIFFICULTY =====");
        sb.AppendLine($"allow-flight={AllowFlight.ToString().ToLower()}");
        sb.AppendLine($"spawn-protection={SpawnProtection}");
        sb.AppendLine($"spawn-radius={SpawnRadius}");
        sb.AppendLine();
        
        // Сеть
        sb.AppendLine("# ===== NETWORK =====");
        sb.AppendLine($"online-mode={OnlineMode.ToString().ToLower()}");
        sb.AppendLine($"prevent-proxy-connections={PreventProxyConnections.ToString().ToLower()}");
        sb.AppendLine($"network-compression-threshold={NetworkCompressionThreshold}");
        sb.AppendLine($"max-tick-time={MaxTickTime}");
        sb.AppendLine($"player-idle-timeout={PlayerIdleTimeout}");
        sb.AppendLine();
        
        // RCON
        sb.AppendLine("# ===== RCON =====");
        sb.AppendLine($"enable-rcon={EnableRcon.ToString().ToLower()}");
        sb.AppendLine($"rcon.password={RconPassword}");
        sb.AppendLine($"rcon.port={RconPort}");
        sb.AppendLine($"rcon.ip={RconIp}");
        sb.AppendLine();
        
        // Query
        sb.AppendLine("# ===== QUERY =====");
        sb.AppendLine($"enable-query={EnableQuery.ToString().ToLower()}");
        sb.AppendLine($"query.port={QueryPort}");
        sb.AppendLine();
        
        // Прочее
        sb.AppendLine("# ===== OTHER =====");
        sb.AppendLine($"white-list={WhiteList.ToString().ToLower()}");
        sb.AppendLine($"enforce-whitelist={EnforceWhitelist.ToString().ToLower()}");
        sb.AppendLine($"enforce-secure-profile={EnforceSecureProfile.ToString().ToLower()}");
        sb.AppendLine($"motd={Motd}");
        sb.AppendLine($"op-permission-level={OpPermissionLevel}");
        sb.AppendLine($"broadcast-console-to-ops={BroadcastConsoleToOps.ToString().ToLower()}");
        sb.AppendLine($"broadcast-rcon-to-ops={BroadcastRconToOps.ToString().ToLower()}");
        sb.AppendLine($"sync-chunk-writes={SyncChunkWrites.ToString().ToLower()}");
        sb.AppendLine($"use-native-transport={UseNativeTransport.ToString().ToLower()}");
        sb.AppendLine($"spawn-npcs={SpawnNpcs.ToString().ToLower()}");
        sb.AppendLine($"spawn-animals={SpawnAnimals.ToString().ToLower()}");
        sb.AppendLine($"spawn-monsters={SpawnMonsters.ToString().ToLower()}");
        sb.AppendLine($"max-chained-neighbor-updates={MaxChainedNeighborUpdates}");
        sb.AppendLine($"hide-online-players={HideOnlinePlayers.ToString().ToLower()}");
        sb.AppendLine($"log-ip={LogIp.ToString().ToLower()}");
        sb.AppendLine($"rate-limit={RateLimit}");
        sb.AppendLine($"force-gamemode={ForceGamemode.ToString().ToLower()}");
        sb.AppendLine($"entity-broadcast-range-percentage={EntityBroadcastRangePercentage}");
        sb.AppendLine($"function-permission-level={FunctionPermissionLevel}");
        sb.AppendLine($"initial-enabled-packs={InitialEnabledPacks}");
        sb.AppendLine($"initial-disabled-packs={InitialDisabledPacks}");
        
        File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
    }

    /// <summary>
    /// Установить свойство по имени
    /// </summary>
    private static void SetProperty(ServerProperties props, string key, string value)
    {
        switch (key)
        {
            case "server-port":
                props.ServerPort = ParseInt(value, 25565);
                break;
            case "server-ip":
                props.ServerIp = value;
                break;
            case "max-players":
                props.MaxPlayers = ParseInt(value, 20);
                break;
            case "view-distance":
                props.ViewDistance = ParseInt(value, 10);
                break;
            case "simulation-distance":
                props.SimulationDistance = ParseInt(value, 10);
                break;
            case "gamemode":
                props.Gamemode = value.ToLower();
                break;
            case "hardcore":
                props.Hardcore = ParseBool(value, false);
                break;
            case "difficulty":
                props.Difficulty = value.ToLower();
                break;
            case "pvp":
                props.Pvp = ParseBool(value, true);
                break;
            case "command-block-enabled":
                props.CommandBlocks = ParseBool(value, true);
                break;
            case "level-name":
                props.LevelName = value;
                break;
            case "level-seed":
                props.LevelSeed = value;
                break;
            case "level-type":
                props.LevelType = value;
                break;
            case "max-world-size":
                props.MaxWorldSize = ParseInt(value, 29999984);
                break;
            case "generate-structures":
                props.GenerateStructures = ParseBool(value, true);
                break;
            case "allow-nether":
                props.AllowNether = ParseBool(value, true);
                break;
            case "allow-flight":
                props.AllowFlight = ParseBool(value, false);
                break;
            case "spawn-protection":
                props.SpawnProtection = ParseInt(value, 16);
                break;
            case "spawn-radius":
                props.SpawnRadius = ParseInt(value, 10);
                break;
            case "online-mode":
                props.OnlineMode = ParseBool(value, true);
                break;
            case "prevent-proxy-connections":
                props.PreventProxyConnections = ParseBool(value, true);
                break;
            case "network-compression-threshold":
                props.NetworkCompressionThreshold = ParseInt(value, 256);
                break;
            case "max-tick-time":
                props.MaxTickTime = ParseInt(value, 60000);
                break;
            case "enable-rcon":
                props.EnableRcon = ParseBool(value, false);
                break;
            case "rcon.password":
                props.RconPassword = value;
                break;
            case "rcon.port":
                props.RconPort = ParseInt(value, 25575);
                break;
            case "rcon.ip":
                props.RconIp = value;
                break;
            case "enable-query":
                props.EnableQuery = ParseBool(value, false);
                break;
            case "query.port":
                props.QueryPort = ParseInt(value, 25565);
                break;
            case "white-list":
                props.WhiteList = ParseBool(value, false);
                break;
            case "enforce-whitelist":
                props.EnforceWhitelist = ParseBool(value, false);
                break;
            case "enforce-secure-profile":
                props.EnforceSecureProfile = ParseBool(value, true);
                break;
            case "motd":
                props.Motd = value;
                break;
            case "op-permission-level":
                props.OpPermissionLevel = ParseInt(value, 4);
                break;
            case "broadcast-console-to-ops":
                props.BroadcastConsoleToOps = ParseBool(value, true);
                break;
            case "broadcast-rcon-to-ops":
                props.BroadcastRconToOps = ParseBool(value, true);
                break;
            case "sync-chunk-writes":
                props.SyncChunkWrites = ParseBool(value, true);
                break;
            case "use-native-transport":
                props.UseNativeTransport = ParseBool(value, true);
                break;
            case "spawn-npcs":
                props.SpawnNpcs = ParseBool(value, true);
                break;
            case "spawn-animals":
                props.SpawnAnimals = ParseBool(value, true);
                break;
            case "spawn-monsters":
                props.SpawnMonsters = ParseBool(value, true);
                break;
            case "max-chained-neighbor-updates":
                props.MaxChainedNeighborUpdates = ParseInt(value, 1000000);
                break;
            case "hide-online-players":
                props.HideOnlinePlayers = ParseBool(value, false);
                break;
            case "player-idle-timeout":
                props.PlayerIdleTimeout = ParseInt(value, 0);
                break;
            case "log-ip":
                props.LogIp = ParseBool(value, true);
                break;
            case "rate-limit":
                props.RateLimit = ParseInt(value, 0);
                break;
            case "force-gamemode":
                props.ForceGamemode = ParseBool(value, false);
                break;
            case "entity-broadcast-range-percentage":
                props.EntityBroadcastRangePercentage = ParseInt(value, 100);
                break;
            case "function-permission-level":
                props.FunctionPermissionLevel = value;
                break;
            case "initial-enabled-packs":
                props.InitialEnabledPacks = value;
                break;
            case "initial-disabled-packs":
                props.InitialDisabledPacks = value;
                break;
        }
    }

    private static int ParseInt(string value, int defaultValue) =>
        int.TryParse(value, out var result) ? result : defaultValue;

    private static bool ParseBool(string value, bool defaultValue)
    {
        // Minecraft использует lowercase true/false
        if (string.Equals(value, "true", StringComparison.OrdinalIgnoreCase))
            return true;
        if (string.Equals(value, "false", StringComparison.OrdinalIgnoreCase))
            return false;
        return defaultValue;
    }

    /// <summary>
    /// Получить описание режима игры
    /// </summary>
    public string GamemodeDisplayName => Gamemode.ToLower() switch
    {
        "survival" => "Выживание",
        "creative" => "Творчество",
        "adventure" => "Приключение",
        "spectator" => "Наблюдатель",
        _ => Gamemode
    };

    /// <summary>
    /// Получить описание сложности
    /// </summary>
    public string DifficultyDisplayName => Difficulty.ToLower() switch
    {
        "peaceful" => "Мирный",
        "easy" => "Легкий",
        "normal" => "Нормальный",
        "hard" => "Сложный",
        _ => Difficulty
    };
}
